### ISSUE TITLE
Get the entire test suite working under rr

### ISSUE THREAD

**Issue by garrison** [JuliaLang/julia#11150]
The goal here is to get the entire julia test suite working under Mozilla's "record and replay framework" (otherwise known as [`rr`](http://rr-project.org/)).  This is likely to help people debug intermittent bugs that only seem to happen on occasion when running the test suite.

Currently, all tests pass except for a few [`profile`](https://github.com/JuliaLang/julia/blob/master/test/profile.jl) and [`spawn`](https://github.com/JuliaLang/julia/blob/master/test/spawn.jl) tests.

- [x] The `profile.jl` tests fail, ~~as the following syscalls are [unimplemented](https://github.com/mozilla/rr/issues/1053) by `rr`: `timer_create`, `timer_settime`, and `timer_delete`~~ hanging with `[rr.8416] Warning: task 16746 (process 16746) dying from fatal signal SIGUSR2.`. (yyc: passes on linux x64 with rr 4.1.0.r111.gef7681a)
- [x] In `spawn.jl`, the line ``@unix_only @test (run(pipe(yes,`head`,DevNull)); true)`` leads to a process `dying from fatal signal SIGPIPE`.  The tests then seem to hang there.
- [x] In `spawn.jl`, the line ``@test_throws Base.UVError run(`foo_is_not_a_valid_command`)`` results in an `ErrorException` instead of `UVError`.
- [x] In `spawn.jl` the four lines beginning with `readall(setenv(` lead to an [assertion failure](https://github.com/mozilla/rr/blob/5d3294a58932f84b0fda92f2ddbb68913a457590/src/Monkeypatcher.cc#L44) within `rr` itself.  This (presumably) is because `rr` expects `LD_PRELOAD` to be set in all subprocesses, but the environment has been cleared by the call to `setenv`.
- [x] `exec` failure is not correctly reported. (Reported upstream as https://github.com/mozilla/rr/issues/1741)
- [x] Opening FIFO blocks indefinitely. (Reported upstream as https://github.com/mozilla/rr/issues/1742)

For many (if not all) of these, the best path forward is simply to disable these tests when running under `rr`.

**Comment by garrison** [comment]
@rocallahan, is there a good way for a program to detect whether it is running under `rr`, and behave slightly differently if so?  At the moment the best "hack" I can think of is to test whether `LD_PRELOAD` contains the string `rrpreload`.

**Comment by rocallahan** [comment]
Yeah, we don't have an officially supported way to do that right now. One approach that we should probably make officially supported is to write data to RR_MAGIC_SAVE_DATA_FD (999) (see rr/rr.h); under rr, that works, but otherwise it normally wouldn't work.

**Comment by rocallahan** [comment]
Please file rr issues on the bugs mentioned above; we should fix them. The timer syscalls would be easy to support. For the others, I'd need some debugging help.

**Comment by rocallahan** [comment]
I added timer_ support in https://github.com/mozilla/rr/commit/a32f60fdaaf3b3c558989005ae33b4c13a835793.

**Comment by timholy** [comment]
This is exciting progress!

**Comment by staticfloat** [comment]
The MIT cloud guys are making sure setting the proper KVM options for this doesn't break anything, and if it turns out okay, then they're going to set it up early next week. I can't guarantee it will work, but I think we've got a good shot at getting the buildbots `rr`-capable.

**Comment by staticfloat** [comment]
Alright, we've got `rr` running on our 32 and 64-bit Ubuntu 14.04 buildbots now.  What is the desired interface here?  An `rr record` output posted for every commit?  A web-accessible button that you can push to run `rr record` on one of the buildbots?  It's not outside of the realm of possibility that we could get pretty close to the "have an ssh session open and waiting", but I don't think we'd be able to do it for every commit.  :P

Pinging @carnaval because it sounded like he was interested in this.

**Comment by yuyichao** [comment]
The whole test suite now passes under `rr` now!

**Comment by garrison** [comment]
Woohoo!  I'm guessing the bootstrap process works now too?

**Comment by yuyichao** [comment]
IIUC the bootstrap has always been working.
