### ISSUE TITLE
Package documentation TODO 

### ISSUE THREAD

**Issue by milktrader** [JuliaLang/julia#11923]
- [x] add information about REQUIRE file https://github.com/JuliaLang/julia/pull/11716
- [x] emphasize importance of tagging packages during registration https://github.com/JuliaLang/julia/pull/11716
- [x] document possible package name bike shedding https://github.com/JuliaLang/julia/pull/11916
- [x] alert readers of general guidelines for registration into METATDATA early https://github.com/JuliaLang/julia/pull/11910
- [x] add information about including a License
- [ ] change `METADATA.jl` to `CuratedPackages.jl` https://github.com/JuliaLang/METADATA.jl/issues/2800

**Comment by kshyatt** [comment]
Have items 3 & 4 been sufficiently addressed here?

**Comment by milktrader** [comment]
The last item is kinda stale so maybe close this issue?
