### ISSUE TITLE
Vectorization Roadmap

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#16285]
Now that #15032 is merged, here are the main remaining steps discussed in #8450, roughly in order that they should be implemented:
- [x] Improve output type-computation in `broadcast` to be at least as good as `map` (#4883).   The trickest part is the ongoing discussion of what to do in the empty-array case (see #11034).
- [x] Deprecate `@vectorized` functions like `sin(x)` in favor of `sin.(x)`. #17302
- [x] Parse operators like `a .+ b` as `broadcast(+, a, b)`.   (See also https://github.com/JuliaLang/julia/pull/6929#issuecomment-44099346, #14544, and #17393.)  Existing overloaded functions `.+(a, b) = ...` can be deprecated in favor of overloading `broadcast(::typeof(+), a, b)`.  #17623

More speculative proposals ~~probably for the 0.6 timeframe~~ (suggested by @yuyichao):
- [x] Define nested `f.(args...)` calls as "fusing" broadcast operations at the syntax level.  For example, `sin.(x .+ cos.(x .^ sum(x.^2)))` would turn (in `julia-syntax.scm`) into `broadcast((x, _s_) -> sin(x + cos(x^_s_)), x, sum(broacast(^, x, 2)))`.   Notice that the `sum` function (or any non-dot call) would be a "fusion boundary."  The caller would be responsible for not using `f.(args...)` in cases where fusion would screw up side effects. #17300
- [x] Define `x .= ...` as "fusing" calls to `broadcast!`, e.g. `x .= sin.(x .+ y)` would act in-place with a single loop.   Again, this would occur at the syntax level, so the caller would be responsible for avoiding function calls with problematic side effects.   (See #7052, but the lack of loop fusion at that time made `.+=` much less attractive.) #17510

**Comment by andyferris** [comment]
Regarding the third point, can we do `.=` as `broadcast!` without worrying overly about loop fusion?

As in `A .= B` as `broadcast!(x->x, A, B)` as an element-wise copy. Of course, more complex expressions would require more complex loop fusion, but this gives some moderate gain. `.+=` and so-on are very low-hanging fruit for at least removing one layer of allocation very simply.

(Hmm... that last one makes me think if `.sin=` is good syntax? As in `A .sin= B` being like Julia 0.4 `A[:] = sin(B[:])` I'm being more than a bit silly here, but it works similarly to the `.` prefix version like `.sin(x)` rather than suffix `sin.(x)`. It even kinda nests: `A .exp.sin= x`. Quite ugly though, and messes with scoping/field syntax)

**Comment by stevengj** [comment]
@andyferris, without loop fusion, an in-place `.=` is pretty useless.  An expression like `x .= 4y .+ 5y.^2 .- sin.(y)` will still allocate lots of temporary arrays.

**Comment by andyferris** [comment]
@stevengj I agree that it is (almost) useless, except for an alternative copy syntax. It's just "step zero" - it's dirt simple and provides the precedence for "step one" as doing similarly for `.+=` and all the other `op=` with a prefix `.`, which then starts to be useful, for things like `x .+= 1` or something to be non-allocating where `x` is an `Array`. In fact, the number of `op=` operators currently defined is relatively small... so it shouldn't be too hard to define them all.

"Step 2" would be the more complex loop fusion or similar, and perhaps generalizations to generic functions. 

On the whole, I do have to support what Jeff said in [#14544 (comment)](https://github.com/JuliaLang/julia/issues/14544#issuecomment-168588296). Perhaps the cleaner approach is to have some neat syntax for `map`/`broadcast` (and hopefully where loop fusion is clear to the user or compiler). I dunno.

**Comment by stevengj** [comment]
@andyferris, that discussion is out of date.  We now do have a neat syntax for `broadcast`, and the possibility for loop fusion is now exposed to the compiler at the syntax level.   And the since that syntax is `.`, dot operators now make a lot more sense.

**Comment by andyferris** [comment]
@stevengj Sorry, I missed the last week or so of #8450 (it's really hard to keep up with all the threads!).

In any case, the progress seems very cool! The parser-based loop fusion (e.g. your [#8450 (comment)](https://github.com/JuliaLang/julia/issues/8450#issuecomment-217890765) seems like a great option to me. Any more complex things can still be done with loops, comprehensions, `map` and `broadcast` explicitly.

**Comment by diegozea** [comment]
A `@fuse`  macro can be more safe than making the loop fusion at parser level, can't it?

**Comment by yuyichao** [comment]
What's the advantage? We already have that `Devectorize.jl` and I don't think It will be more flexible or give you more control.

**Comment by diegozea** [comment]
I'm only worry about making loop fusion everywhere. *"The caller would be responsible for avoiding function calls with problematic side effects"* but... How can the user use the point notation and avoid the fusion at the same time? Also I think that `@fuse` will be more explicit to write and to read in the code. `@fuse` can do the same loop fusion proposed, but It can also check the functions to be called (i.e. annotated pure functions).

**Comment by yuyichao** [comment]
> The caller would be responsible for avoiding function calls with problematic side effects

I think this is not an issue for the majority of cases.

> How can the user use the point notation and avoid the fusion at the same time?

Split the line

> but It can also check the functions to be called (i.e. annotated pure functions).

This is impossible. Or at least it be better at doing that.

**Comment by stevengj** [comment]
@diegozea, macros operate at the syntax level, without knowing types, so they can't check pureness.

Think of `f.(args...)` as a much more compact and discoverable syntax for `@fuse`.   (Once we deprecate e.g. `sin(x)` in favor of `sin.(x)` etcetera, people doing Matlab-like computations will end up using fused loops automatically in many case due to the deprecation warning, whereas they might never learn about `@fuse`.)

**Comment by stevengj** [comment]
Another way of saying it is that fusing the loops is a good idea in the vast majority of cases.  *Not* wanting to fuse is the rare exception.   That makes it sensible to make fusing the default, and in the rare cases where you don't want to fuse you can either split the line or just call `broadcast` explicitly.

**Comment by diegozea** [comment]
Sorry, I meant  *parse* not *syntax* level in my last sentence. However I believed that a macro could access a function metadata.

**Comment by yuyichao** [comment]
> However I believed that a macro could access a function metadata.

No it can't. For a start, it doesn't even have any idea about the binding. It is allowed to do `sin = cos; sin(1)` (or a much more reasonable for of this). `@pure` is also per method and you can't check that without knowing all the type info.

**Comment by stevengj** [comment]
@diegozea, macros *are* called at the parse level, which is what we mean by the "syntax" level here.  i.e. at the point the macro is called, *all* that is known is the abstract syntax tree (AST).

**Comment by martinholters** [comment]
While fusion by default sounds like a good idea, I find it a bit unsettling that
```Julia
y = g.(f.(x))
```
and
```Julia
a = f.(x)
y = g.(a)
```
might give different results. Is that just me?

**Comment by nalimilan** [comment]
Not different results, just different ways of returning the same result. That's fine IMHO. In the long-term, the compiler might become smarter and detect more complex cases.

**Comment by martinholters** [comment]
@nalimilan You are assuming pure f and g.

**Comment by johnmyleswhite** [comment]
FWIW, I suspect most functions people are vectorizing are pure.

**Comment by quinnj** [comment]
Maybe we need to do some more exploration around function traits (purity, guaranteed return types, boolean, etc.) and how they could be incorporated into some of these murkier discussions (vectorization, return types, etc.). It seems like having some explicit declarations around function traits would avoid the need to rely on inference or the compiler.

**Comment by andyferris** [comment]
I'm worried that overly complex rules for defining how loop fusion works will just become too confusing for users. The suggestion that `A .= B .+ B ...` becomes *syntactic sugar* for `map`/`broadcast` means that, once we are all used to it, we will easily be able to reason about code we see and know how to write a simple fused loop expression for vectors of data.

If it is a simple parsing-level rule, then the differences in @martinholters's comment will be obvious. If it is compile-time magic, we will be spending a lot of time trying to figure out if the compiler is really doing what we want it to do.

But coming back to nested `.` functions/operators, would we be able to avoid allocation when matrix multiplication is in the middle, e.g. `v1 .= v2 .+ m1*v3` (where `m3` is a matrix, and `v*` are vectors). Correct me if I'm wrong, but isn't this BLAS's `daxpy`? We would want that to be non-allocating, so *hopefully* whatever syntax we come up with would allow for this kind of thing (where the order of multiplication and additions for the matrix multiplication is cache-optimized as-in BLAS, not direct as-in `map` and `broadcast`).

**Comment by yuyichao** [comment]
@andyferris Yes, the hope is that the parser level transformation can cover most use case with a well defined schematics. It is in principle possible to add support for more complicated construct (I very briefly talked about this with @andreasnoack ) but I personally feel like it is hard to come up with a syntax that can cover all the cases besides what can be currently achieved with `broadcast` (or a mutating version of it).

Thinking loudly, maybe it can be achieved by having a lazy array type (so the computation is done on the fly with in `boardcast`)? That would be an orthogonal change though. It'll also be hard to recognize that and call `BLAS` functions.

**Comment by stevengj** [comment]
@andyferris, the whole point is that the proposed loop fusion becomes a simple parsing-level guarantee, not compile-time at all.    If you see `f.(g.(x))`, then you know that the loops are *always* fused into a single `broadcast`, regardless of the bindings of `f`, `g`, or `x`.   This allows you to reason simply about the code consistently.

This is *very* different from a compile-time optimization that may or may not occur.

**Comment by andyferris** [comment]
@stevengj Yes, I understand and agree completely (my first two paragraphs were directed at @quinnj). 

>  the whole point is that the proposed loop fusion becomes a simple parsing-level guarantee, 

To my taste, the keyword is "guarantee". I really do like it.

I was more thinking along the lines of what @yuyichao was thinking "loudly". If Matrix-Vector multiplication was lazy (returned an iterable over `i` for `sum(M[i,:] .* v)` or similar) then it would "just work" with no temporaries given a combination of your suggested changes to the parser and introducing the lazy multiplication type (and thus no "compile-time optimizations" are necessary beyond what already exists in Julia). It would be interesting to compare performance to `daxpy`.

(of course, when you say "compile-time" optimization I interpret that as changes to compilation after lowering, not changes to definitions in `Base.LinAlg`.)

A similar thing for Matrix-Matrix multiplication is much, much harder. Although we could have arbitrarily clever iterators, they might or might not be not be the correct thing to reimplement a somewhat efficient `dgemm` in native Julia, or to call out to it "automagically". But this is definitely something worth considering for the future, and for the development of syntax, because superfluous temporaries after multiplying matrices (along with adding them, etc, which hopefully will be fixed in this roadmap) is IMHO currently one of Julia's numerical performance bottlenecks when working with very large matrices/tensors/etc. (On that note, does an interface for `dgemm!` currently exist for the memory-constrained users that want to extract the last bit of efficiency out of Julia?)

**Comment by StefanKarpinski** [comment]
@stevengj: are you planning on tackling this or should we figure out who else can tackle it?

**Comment by stevengj** [comment]
I'm planning on tackling the loop fusion.   The other parts require someone to improve the type computation in `broadcast` (similar to #16622), and I was hoping someone else would tackle that.  😊

**Comment by StefanKarpinski** [comment]
If we don't implement "syntactic fusing" for 0.5 (status, @stevengj?) and plan on implementing it in a future version, we should amply document that this will change in the future and note that people should only use nested broadcasting in cases where such a transformation would not change the meaning.

Otherwise the only change above that seems to be slated to make it into 0.5 is the improvement of the output type computation.

**Comment by JeffBezanson** [comment]
We will only do #4883 for 0.5. That issue is part of the milestone, so moving this to 0.6

**Comment by stevengj** [comment]
Sorry, I've been traveling for multiple weeks; just got back yesterday.

**Comment by ViralBShah** [comment]
We missed you at JuilaCon.

**Comment by s-broda** [comment]
I wonder whether rather than just deprecating ``log(a::Array)`` and friends (#17302), a better use of the fact that #17300 frees up this syntax wouldn't be to make it syntactic sugar for calling a vector math library, leveraging the unified call syntax from @rprechelt's ``vectorize.jl``. Wouldn't it be a bit silly to have to write ``@vectorize log.(a::Array)`` to `re-vectorize' the call?

I suppose the main drawback would be that it would make the log.(a:Array) syntax less discoverable, but I submit that it's even less likely that a Matlab convert would discover the @vectorize macro on their own, leaving a ~7x speed boost on the table.

**Comment by martinholters** [comment]
@s-broda If there are better (faster) implementations for certain operations, one can always add a specialized method, like `broadcast(::typeof(log), a::Array{Float64})=...` to use that for `log.(A)`.

**Comment by s-broda** [comment]
@martinholters Fair enough. Is there any advantage to special casing it there versus defining a new method for log(a::Array) that I'm missing? 

I'm not sure that this is simply a faster implementation, as there may be a 1 or 2 ULP difference between the the current implementation and using a vector math library. That's why I thought that having a special (convenient) syntax that reflects the difference in semantics might be useful.

**Comment by stevengj** [comment]
@s-broda, the plan is for `log(a::Array)` to go away.   It's extremely useful to expose the user's intention of an element-wise broadcast at the syntax level, with `log.(a)`, because that enables loop fusion, in-place operations, and other transformations that are very difficult to do at later compilation stages if the compiler has to figure out things on its own.

**Comment by s-broda** [comment]
@stevengj I think there is a misunderstanding here. I couldn't agree more about the usefulness of the sin.(a) syntax, for precisely the reasons that you mention - indeed it's the one feature that I've been crossing my fingers would make it into 0.5, and I couldn't be more thrilled that you tackled it so quickly. My point was rather the opposite: namely, that _because_ this effectively frees up the sin(a::Array) syntax, the now redundant sin(a::Array) could now be made syntactic sugar for calling into Accelerate/Yeppp!/VML in cases where no loop fusion is required. This, too, could thus happen at the syntax level, rather than relying on the compiler or calling Accelerate/Yeppp!/VML explicitly.

I suppose I should have raised this on the mailing list rather than here, sorry.

**Comment by stevengj** [comment]
@s-broda, that's not syntactic sugar, that is just an ordinary method, and requires nothing new in the language; you'll still be able to define `foo(a::Array)` methods if you want, regardless of the `foo.(a)` support.

**Comment by davidanthoff** [comment]
@s-broda And that could be done easily in a package.

**Comment by toivoh** [comment]
I would like to argue that once we stop supporting `sin(a::Array)`, it should give an error, period (with an error message that tells you to use `sin.(a)`, if possible).

Just because we stop supporting it doesn't mean that people will stop trying to use it, and we want them to get the error message to know that is not the intended way. Also, I really don't think that loading a package should change the behavior of code that doesn't use it.

**Comment by tkelman** [comment]
Agreed, the standard "type piracy" guideline is that a package should not extend base methods except on types defined by that package.

**Comment by stevengj** [comment]
Funnily enough, it turns out that the "more speculative" 0.6 proposals were actually easier to implement.  Or more fun, at least, since they don't affect backwards-compatibility much.

**Comment by StefanKarpinski** [comment]
Life is so breezy when you don't have to worry about breaking people's code. Those were the days!

**Comment by ViralBShah** [comment]
I guess deprecating the old behaviours is something that should still wait.

**Comment by stevengj** [comment]
@ViralBShah, yeah, it's way too late in the 0.5 cycle for a massive deprecation.

**Comment by bramtayl** [comment]
It's pretty easy to write hijackable versions of broadcast. This would allow using the loop fusion mechanism to fuse loops for any function that would benefit from loop fusion, like `filter` or `mapslices`. I think? all that would be required is using the two functions below instead of the regular versions of `broadcast` with the dot syntax.

```{julia}
function maybe_broadcast(args...; f = broadcast)
  f(args...)
end

function maybe_broadcast!(args...; f = broadcast!)
  f(args...)
end
```

**Comment by stevengj** [comment]
How exactly would `filter(f, g.(args...))` be able to use loop fusion?  It seems like the parser would have to know about the `filter` function.

**Comment by bramtayl** [comment]
Maybe I'm missing something. Wouldn't

```{julia}
a.(b.(c.(A)))
```

turn into

```{julia}
maybe_broadcast(x -> a(b(c(x))), A, f = filter)
```

turn into

```{julia}
filter(x -> a(b(c(x))), A)
```
?


```

**Comment by stevengj** [comment]
@bramtayl, no, it would turn into `maybe_broadcast(x -> a(b(c(x)); _f = filter), A)`

**Comment by stevengj** [comment]
It seems like we'd need a new syntax, like `filter..(a.(b.(c(A)))`.

**Comment by bramtayl** [comment]
darn. well that syntax seems nice?

**Comment by stevengj** [comment]
Don't take my offhand syntax suggestions too seriously!  It would take a while and a lot of thought to hash out what the implications and semantics would be, and to decide whether a new syntax is really worth it vs. just typing `filter(x -> a(b(c(x))), A)`.   See #8450 for how long it took to settle on `f.(args...)`.

**Comment by stevengj** [comment]
I feel like maybe we should have a "vectorization" label to group issues and PRs related to this stuff?

**Comment by ViralBShah** [comment]
Label created and applied here.

**Comment by tkelman** [comment]
but does the label mean syntax vectorization or SIMD vectorization?

**Comment by quinnj** [comment]
How about a SIMD label?

**Comment by stevengj** [comment]
My thinking was for vectorization at the syntax and library level, not at the instruction level (SIMD).

**Comment by stevengj** [comment]
For interest, here is Chapel's solution to loop fusion of element-wise operations: [zippered iterators](http://pgas11.rice.edu/papers/ChamberlainEtAl-Chapel-Iterators-PGAS11.pdf).

**Comment by stevengj** [comment]
And here is [ZPL's approach](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.46.6627), though it sounds like it is limited to built-in vectorized operations in the language.

**Comment by stevengj** [comment]
@bramtayl, the more I think about it, the more I think that you're right and it would be a good idea to support syntactic fusion for more operations than just `broadcast` — the same semantics, just a way to substitute another function for `broadcast` in the lowered expression.  Most other people looking at fusion in array languages seem to worry about reduction operations, for example.   And in some ways it seems contrary to Julia's spirit to have a single "blessed" function, `broadcast`, "baked" into the language in a manner that cannot be replicated by a user-defined function.

It would be nice to use some kind of dots, as a syntactic reminder of the connection to dot calls, and `foo..(args...)` is available.  e.g. `sum..(sin.(3 .+ x.^2))` would be equivalent to `sum(_ -> sin(3 + _^2), x)`. 

Questions:

* How would you pass additional arguments, e.g. the reduction operator to `reduce`?  Maybe the fusion would only occur on the last argument?   So e.g. `reduce..(+, sin.(3 .+ x.^2))` would be equivalent to `reduce(_ -> sin(3 + _^2), +, x)`?   Is this flexible enough?

* How would it interact with `.=`, if at all?

* Is there a better syntax?  The other one that comes to mind is `:`, as in `sum:(sin.(3 .+ x.^2))`, but I'm worried about the ambiguity with `... ? ... : ...`.

* @ViralBShah, @StefanKarpinski, is this something worth considering?

Given a choice of syntax etcetera, the implementation of something like `sum..(f.(args...))` seems like it should be pretty trivial ... I don't think it will require more than 10 lines in `julia-syntax.scm`.

**Comment by bramtayl** [comment]
I'm just happy to have had a reasonable idea for once! I think it would be helpful to follow the original syntax. So

`reduce..(sin.(3 .+ x.^2), +)`
would turn into
`reduce..(sin.(3 .+ x.^2), +, x)`

more generally,
`f..(dotted_expression, args...; kwargs...)` would turn into
`f..(function_version_of_dotted_expression`, args..., mapped_over_objects...; kwargs...)`

`dotted_expression` by itself would be sugar for
`broadcast..(dotted_expression)`

**Comment by stevengj** [comment]
The biggest problem in my mind is the broadcast semantics.   e.g. if `x` is a row vector and `y` is a column vector, then `x .+ y` produces a matrix, but if `sum..(x .+ y) turns into `sum(+, x, y)` it seems like the `sum` function will have to implement the whole `broadcast` machinery in order to give the result most people would expect.

**Comment by bramtayl** [comment]
Hmm, well, there could also be a `lazy_match_shape` function automatically applied, which would take all the args in what I called `mapped_over_arguments` above and replace them with non-traditionally indexed versions of themselves, such that, if `x` is a row vector and `y` is a column vector, `x[2, 2]` would be `x[2]` and `y[2, 2]`, would be `y[1, 2]`

**Comment by bramtayl** [comment]
There is also the possibility of trying to get multiple `..` calls to work together. Like 
`reduce..(broadcast..(mapslices..(...), ...)...)`

**Comment by andyferris** [comment]
> it would be a good idea to support syntactic fusion for more operations than just broadcast

How about a macro (in `Base`), like `@reduce`, so that `@reduce(+, A .+ B)` will replace `broadcast` with `mapreduce` (we possibly need a `broadcastreduce()` function?). Seems simplest to me, and it should more-or-less preserve the meaning of `.op`.

There could be another macro which changes the meaning of the `.op`, like `@fuse(f, expr)`.

**Comment by stevengj** [comment]
@andyferris, unfortunately macros alone can't do this, since they only see the syntax before lowering, whereas the conversion of dot calls to `broadcast` happens during lowering.

**Comment by andyferris** [comment]
@stevengj Right, but why does that matter? The macro would just have to do a little more work: by-parsing (pun intended...) lowering by implementing the exact same rules but at the macro level, transforming the `.+` and `.()` etc the correct way. Or by doing something a bit different to `broadcast`, but similar enough that it makes sense (like the `@reduce` macro I suggested above).

(On a side note, this is making me wonder whether fusing at the language level is strictly necessary, since a macro (in `Base`) can do it. The important bit is defining the meaning of `.()` and `.op` to use `broadcast` and `.=` to use `broadcast!` - we can easily add a `@fuse` macro to v0.5 (to get the fusing behaviour for `.op` that we expect to see in v0.6) with zero breakage...).

**Comment by blairn** [comment]
I'm finding this all very confusing, I've followed to this thread from a request for some way to infix the map function so we can do something like

[1,2,3,4] .|> times2 |> sum

would this mean it is...

[1,2,3,4] |> times2. |> sum? or something else?

**Comment by bramtayl** [comment]
@blairn I have reasonable ways to do things like that, I think, in ChainMap.jl

**Comment by blairn** [comment]
I end up with something that looks like.
remap(f) = x -> map(f,x)
repmap(f) = x -> pmap(f,x)

then [1,2,3,4] |> remap(times2) |> sum

Except, the chains are about 10 functions long, and have a bunch of Geospatial transforms all through it.

I'll have a look at ChainMap, but I was hoping people would remember where a lot of the requests for this stuff came from. Things seems to have gone well away from the original requests - not in a bad way, but I am worried that we will end up with something which will end up with a bunch of old issues being reopened.

**Comment by stevengj** [comment]
@andyferris, I'd hate to see the requirement for `@fuse` macros sprinkled all over the place.  And since the semantics depend on whether `f.(g.(x))` is fusing or non-fusing, it's hard to change our minds and make it fusing later if it is non-fusing now.

**Comment by andyferris** [comment]
> I'd hate to see the requirement for @fuse macros sprinkled all over the place

@stevengj Very true - I'd prefer it to be automatic. My primary comment was that things *other* than `broadcast` can be achieved with a macro rather than `..` syntax (it was just a side note that we *could* use a fusion macro, though as you point out there may be semantic challenges).

**Comment by bramtayl** [comment]
Another cool thing to do would be to convert


'x .= reduce..(args...)' to
'reduce!(x, args...)'

for any functional programming function. To do that would probably require solving the syntax mess around !. Perhaps '!' could call a 'inplace(f, args...)' function with specialized code for different f function types.

**Comment by bramtayl** [comment]
After further thought,

```julia
reduce..(broadcast..(mapslices..(args1...)args2...)arg3...)
```

could do something like call

```julia
function_fuse(typeof(reduce), typeof(broadcast), typeof(mapslice))(args1, args2, args3)
```

Where, for example,
```julia
function_fuse(typeof(reduce), typeof(map)) = mapreduce
```

**Comment by stevengj** [comment]
The parser can just as easily add a `!` rather than transforming to a call to `inplace`.  Either way, however, it is assuming that the requisite method exists.

**Comment by bramtayl** [comment]
Note that the master version of ChainMap.jl has experimental for "woven" functional programming.

**Comment by bramtayl** [comment]
OK, I've gotten ChainMap into a place where it's relatively stable, and I'd like to propose an alternate method of dot vectorization based on the work there.

Here's an alternative.

- A type, LazyCall, which contains both a function and it's arguments.
- An @~ macro to create a LazyCall from a woven expression (this is currently @unweave in ChainMap)
- New methods for map, broadcast, etc. which take LazyCalls.

Here's how the syntax would change:

`map( ~ sin(~x + y) )` goes to `map( LazyCall(x -> sin(x + y), x) )`
`broadcast( ~ sin(~x + ~y) )` goes to `broadcast( LazyCall( (x, y) -> sin(x + y), x, y) )`
`mapreduce( ( ~ sin(~x + y) ), +)` goes to `mapreduce( LazyCall( x -> sin(x + y), x), +)`

`~ f( ~(x...) )` goes to `LazyCall( (x...) -> f(x...), x...)`
`~ f( ~(;x...) )` goes to `LazyCall( (;x...) -> f(;x...); x...)`

Advantages over the current system:
1) No ambiguity over what counts as a scalar and what doesn't
2) Reduction in the amount of dots necessary for a complicated expression
3) Support for non-broadcast operations
4) Support for using passing multiple LazyCalls to one function
5) Partial support for lazy evaluation
6) Better handling of splats

Disadvantages:
1) ~ is already taken as bit negation. @~ is taken for formulas. I like the symbol because it reminds me of a woven thread. But maybe another ascii character will do?
2) Not backwards compatible; people will need to learn a new system.
3) Less verbose
4) Not sure about performance impacts

All of this is implemented in ChainMap at the moment, aside from the new methods for map and friends. It can probably stay in a package for now if people aren't interested in adding it to base.

**Comment by ChrisRackauckas** [comment]
>map( ~ sin(~x + y) ) goes to map( LazyCall(x -> sin(x + y), x) )
broadcast( ~ sin(~x + ~y) ) goes to broadcast( LazyCall( (x, y) -> sin(x + y), x, y) )
mapreduce( ( ~ sin(~x + y) ), +) goes to mapreduce( LazyCall( x -> sin(x + y), x), +)

I'm sorry, but I'm not seeing how this proposal would clean up code at all. What would `~x + ~y` be? And 

>2) Reduction in the amount of dots necessary for a complicated expression

Would be true, but there wouldn't be less `~` then there were `.`.

**Comment by andyferris** [comment]
While we are on the topic of new ideas, yesterday @c42f and I had some fun playing with the idea of "destructuring" an array.

Sometimes you have a vector of composed types ("structs"), and you might want to refer to the all the values of a certain field. Consider this operation and potential syntax we could implement here with the dot-call idea:

```julia
v::Vector{Complex{Float64}}

# get the real components using current syntax
broadcast(x -> x.re, v) 
broadcast(x -> getfield(x, :re), v)  # alternative syntax

# Kind-of works, but need to add scalar-size methods to `Symbol` 
# Also is slow because it doesn't inline the :re properly
getfield.(v, :re) 

# Potential new convenience syntax (dot call on dot reference):
v..re
```

There is also the same thing, but you might have a vector of tuples or a vector of vector, and we can currently do something like
```
v::Vector{Vector{Int}}

# get the first elements
getindex.(v, 1)

# potential new syntax
v.[1]

v_tuple::Vector{Tuple}

# Doesn't seem to be optimal speed (tuple indexing with Const is special)
getindex.(v_tuple, 1)
```

To conclude: as a performance fix we could (probably should) support faster `getfield.()` for vectors of structs and faster `getindex.()` of vectors of vectors.

As a new syntax proposal, we might consider supporting operators `..` and `.[]` as broadcasted syntax of `getfield` and `getindex` respectively.

**Comment by bramtayl** [comment]
@ChrisRackauckas 

Agreed, less verbose, more flexible.

`~x + ~y` would just be `~x + ~y` (it doesn't passing through a macro)
`~ ~x + ~y` would be `LazyCall( (x, y) -> x + y, x, y)`

In some cases, the amount of dots compared to ~ is cut down on. Eg.
`sin.(cos.(tan.(x .+ 1)` vs `broadcast( ~ sin(cos(tan( ~x + 1)`

**Comment by ChrisRackauckas** [comment]
But `broadcast( ~ sin(cos(tan( ~x + 1) ) ) )` is still a much worse option because `broadcast` should not be in the mathematical expression. The syntax is to get rid of the "programming" from the "math".

**Comment by ChrisRackauckas** [comment]
Also, I don't see the reason for the `LazyCall` in this case. Making the type and the tuple container for the arguments adds to the amount of allocations, when what we really want is simple syntax for allocation-free code.

**Comment by bramtayl** [comment]
Agreed that some of the pure math aspect of things gets lost.

There are allocation free ways of going about this:

`map( ~ sin(~x + y) )` goes to `map( x -> sin(x + y), x)`
`broadcast( ~ sin(~x + ~y) )` goes to `broadcast( (x, y) -> sin(x + y), x, y)`
`mapreduce( ( ~ sin(~x + y) ), +)` goes to `mapreduce( x -> sin(x + y), +, x)`

And in fact, ChainMap has some macros for doing this:

`@map sin(_ + y)` goes to `map( _ -> sin(_ + y), _)` (`_` is used as part of the chaining)
`@broadcast sin(~x + ~y)` goes to `broadcast( (x, y) -> sin(x + y), x, y)`

But to do this you need to make assumptions about argument order (put the anonymous function first, the woven arguments last).

**Comment by StefanKarpinski** [comment]
@bramtayl: if you've got a counter-proposal, you should open an issue or start a julia-dev thread.

**Comment by bramtayl** [comment]
Ok, see #18915

**Comment by wsshin** [comment]
I have a couple of questions about the third goal in this vectorization roadmap, which is to "parse operators like `a .+ b` as `broadcast(+, a, b)`".  

- Now that `broadcast()` works for tuples, will we have `a .+ b` for tuples `a` and `b` when the third goal is achieved?
- Currently `broadcast(+, a, b)` is ~4 times slower than `a .+ b` for vectors `a` and `b`.  (See the benchmark result below.)  Is this going to be fixed before the third goal is achieved?
```
julia> using BenchmarkTools

julia> @benchmark [1,2,3] .+ 1
BenchmarkTools.Trial:
  memory estimate:  224.00 bytes
  allocs estimate:  2
  --------------
  minimum time:     109.144 ns (0.00% GC)
  median time:      152.579 ns (0.00% GC)
  mean time:        203.520 ns (19.59% GC)
  maximum time:     5.679 μs (94.30% GC)
  --------------
  samples:          10000
  evals/sample:     916
  time tolerance:   5.00%
  memory tolerance: 1.00%

julia> @benchmark broadcast(+, [1,2,3], 1)
BenchmarkTools.Trial:
  memory estimate:  320.00 bytes
  allocs estimate:  6
  --------------
  minimum time:     583.749 ns (0.00% GC)
  median time:      599.648 ns (0.00% GC)
  mean time:        784.025 ns (14.38% GC)
  maximum time:     74.077 μs (98.31% GC)
  --------------
  samples:          10000
  evals/sample:     179
  time tolerance:   5.00%
  memory tolerance: 1.00%
```

The above benchmark results were obtained with the following Julia version:
```
julia> versioninfo()
Julia Version 0.6.0-dev.1565
Commit 0408aa2* (2016-12-15 03:02 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin16.0.0)
  CPU: Intel(R) Core(TM)2 Duo CPU     T9900  @ 3.06GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Penryn)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, penryn)
```

**Comment by stevengj** [comment]
@wshin, yes, `.+` etcetera now works for tuples, but it probably needs some performance work in that case.

```jl
julia> (3,4,5) .+ 7
(10,11,12)

julia> (3,4,5) .+ (8,9,10)
(11,13,15)
```

As for your benchmark, currently there is an inlining failure that is slowing down `broadcast` (#19608) that should hopefully be fixed soon. As a result, for very small vectors, the overhead is significant.

(Of course, for very small vectors like `[1,2,3]` you will always get better performance from StaticArrays.jl, since in StaticArrays the *length* of the vector is known at compile-time too, and the entire loop can be unrolled and inlined, not to mention that the result does not need to be heap-pallocated)

**Comment by stevengj** [comment]
Closing, since all items are now merged.

Further improvements are possible, such as a generic syntax like `sum:(x .+ 5)` for fusing any function, making `x[x .> 5]` fusing, and so on, and of course performance improvements (e.g. @Sacha0's planned work on improving sparseness preserving in `broadcast`), but they can have their own issues marked with the *vectorization* label.

**Comment by stevengj** [comment]
(By the way, the performance problems noted by @wsshin were fixed by #19639.)
