### ISSUE TITLE
META: GPU support

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#23639]
Summarizing the action points from this week's meeting on GPU support.

## Essential

- [ ] Contextual method overloading

    The consensus here is that [Cassette.jl](https://github.com/jrevels/Cassette.jl) is the way forward, but for it to be GPU compatible the code it generates needs to be better optimized.

- [ ] BinDeps2 with access to the Julia build tree

## Important

- [ ] Codegen reusability: avoid state, better entry-points
- [ ] Stability guarantees of external language interface (`llvmcall`, codegen entry-points)

## Low-priority

- [ ] Package load times: initial kernel compilation is really slow due to compiling
  CUDAnative/LLVM
- [ ] GC memory pools for GPU allocations
- [ ] Precision of literal numbers (could be done with a Cassette pass)
- [ ] IPO-safety of codegen (TBAA, GC invariant pass)

**Comment by andreasnoack** [comment]
Should there be issues for each of these action points? It would probably be good for tracking progress and for focusing discussions.

**Comment by ViralBShah** [comment]
Yes, I think it would be valuable to have specific issues, and milestones.
