### ISSUE TITLE
Cassette Compatibility

### ISSUE THREAD

**Issue by jrevels** [JuliaLang/julia#25492]
A few core developers have some exciting packages in the works for the Julia 1.x timeframe that rely on [Cassette](https://github.com/jrevels/Cassette.jl) to implement native language AD, GPU transpilation, auto-parallelization, developer tooling, and PL research.

At the moment, however, Cassette's usability is blocked on certain Julia compiler improvements/features. Since the new language-level capabilities Cassette provides are planned dependencies in many areas of the Julia ecosystem, it was decided during the biweekly ML developer meeting that we should prioritize Cassette compatibility for Julia's 1.1 release.

Here are the key items that need to be addressed in Julia itself for Cassette compatibility:

- [ ] https://github.com/jrevels/Cassette.jl/issues/6: world age validation for certain generated functions
- [ ] https://github.com/jrevels/Cassette.jl/issues/7, https://github.com/jrevels/Cassette.jl/pull/14: generated `CodeInfo` inlining should happen in Base rather than in Cassette
- [ ] https://github.com/JuliaLang/julia/pull/24852: support for spoofing inference's work-limiting heuristics (basically done, but blocked on review from the compiler team)
- [ ] https://github.com/jrevels/Cassette.jl/issues/5, https://github.com/JuliaLang/julia/issues/5402: splatting/varargs optimizations

I'll update these issues as new things crop up. I can also move issues from Cassette's tracker to Base's tracker if that's helpful. 

Some of these items (especially performance-related issues) might require significant follow-on work. For example, https://github.com/JuliaLang/julia/pull/24852 currently does provide a mechanism for inference spoofing, but does not update all of inference to leverage that mechanism.

Luckily, since much (if not all) of this work does not incur API breakage, it can be worked on and merged basically at any time (including during the 1.0-dev period).

While the official milestone here is Julia 1.1, that's more of a late deadline; it would be highly beneficial for us to finish as much as possible by 1.0 for two reasons: 

1. There's a lot of Cassette-based work we'd like to be able evangelize at various conferences throughout 2018, and we'd hate for Julia to get scooped by similar work implemented in "lesser" languages. As brought up by @maleadt, the earliest of these is GTC 2018 in late March. We'd hate for Julia to be late to the game for some of these opportunities. 

2. JuliaCon has always been a huge catalyst for development - it's well known that a week at JuliaCon is equal to months of non-JuliaCon development 😉 Thus, we'd like to have stable releases of Cassette and downstream tools (like [Capstan](https://github.com/JuliaDiff/Capstan.jl)) to introduce to the wider community at this time.

**Comment by jrevels** [comment]
I've added https://github.com/JuliaLang/julia/issues/22051 and https://github.com/JuliaLang/julia/issues/11840 to the checklist here, though we can probably get by with just fixing https://github.com/JuliaLang/julia/issues/22051 (according to @vtjnash, fixing https://github.com/JuliaLang/julia/issues/11840 would likely require a nontrivial subtyping redesign). 

https://github.com/JuliaLang/julia/pull/26826 fixes most of the performance/inference issues Cassette that hits, but the improvements to inference cause https://github.com/JuliaLang/julia/issues/11840 to expose itself heavily in Cassette-ified code. Most practical offending cases, however, seem to come from https://github.com/JuliaLang/julia/issues/22051, which can and should be fixed by correcting the currently incorrect implementations of various tuple-handling functions. This should be relatively doable, and further improve Base anyway.

**Comment by jrevels** [comment]
Okay, everything on the TODO list here is marked resolved. It's looking like we might actually have a v0.7 that's Cassette-compatible (fingers crossed). 

Unfortunately, one of the TODO items that was resolved regressed when the new optimizer was merged. This is probably my fault - I likely ported the relevant optimization to the new optimizer incorrectly in #26981. For more info, see https://github.com/jrevels/Cassette.jl/issues/45. As a side note, fixing this optimization should help performance of varargs functions all over the place, not just Cassette - it should, for example, cause some broken sparse array broadcast tests to start passing. I'll try to tackle this last regression in the upcoming week. 

Once we get that issue resolved, we should be able to mark this issue as resolved.

**Comment by ViralBShah** [comment]
It seems that we will need to start thinking about stability for the compiler API. Agree that picking a good workable solution for now is the right direction.
