### ISSUE TITLE
Documenting all exports from Base

### ISSUE THREAD

**Issue by mbauman** [JuliaLang/julia#26919]
It'd be nice to make sure that all our exports are documented and make sense for the 1.0 release.  This is a fairly daunting list, but it is a task that's easily parallelizable and can be tackled incrementally.

There are two classes of undocumented thing.
* It's just plain undocumented.  Add documentation!
* ~It's a callable thing and all its methods live within `deprecated.jl`.  In this case, we probably want to `@deprecate_binding` the binding itself so packages that extend these methods won't be totally surprised when the binding gets removed in 1.0.~

I've written a quick and simple script that identifies these two cases and spits out the list.  Please feel free to jump in and add PRs to resolve these as you are able!  Just be bold and go for it!

```julia
julia> searchdocs(mod) = searchdocs!(Any[], Bool[], mod)
       function searchdocs!(objs, isalldep, mod, seen=Set())
           mod in seen && return
           push!(seen, mod)
           for name in names(mod)
               isdefined(mod, name) || continue
               Base.isdeprecated(mod, name) && continue
               b = getfield(mod, name)
               docs = Base.Docs.doc(Base.Docs.Binding(mod, name))
               if startswith(string(docs), "No documentation found")
                   push!(objs, string(mod, '.', name))
                   push!(isalldep, !isempty(methods(b)) && all(x->occursin("deprecated", something(functionloc(x)[1],"")), methods(b)))
               end
               b isa Module && searchdocs!(objs, isalldep, b, seen)
           end
           objs, isalldep
       end
searchdocs! (generic function with 2 methods)

julia> objs, isalldep = searchdocs(Main)

julia> println("### Undocumented exports")
       foreach(x->println("* [ ] `", x, '`'), objs[.!isalldep])
       println("### Undocumented exports that are entirely deprecated")
       foreach(x->println("* [ ] `", x, '`'), objs[isalldep])
```
### Undocumented exports (including module exports)

* [ ] `Base.Broadcast.dotview`
* [ ] `Base.CanonicalIndexError`
* [ ] `Base.CapturedException`
* [ ] `Base.Docs.@var`
* [ ] `Base.InvalidStateException`
* [ ] `Base.Libc.FILE`
* [ ] `Base.Sys.CPU_NAME`
* [ ] `Base.Sys.JIT`
* [ ] `Base.Sys.cpu_info`
* [ ] `Base.Sys.cpu_summary`
* [ ] `Core.ConcurrencyViolationError`
* [ ] `Core.Exception`
* [ ] `Core.GlobalRef`
* [ ] `Core.IO`
* [ ] `Core.LineNumberNode`
* [ ] `Core.Method`
* [ ] `Core.SegmentationFault`
* [ ] `Core.TypeVar`
* [ ] `Core.WeakRef`
* [ ] `Core.getglobal`
* [ ] `Core.setglobal!`
* [x] `Core.VecElement`
* [x] `Core.DataType` (#24561)
* [x] `Core.Type` (#24561)
* [x] `Base` (#31131)
* [x] `Base.AbstractDict` (https://github.com/JuliaLang/julia/pull/31206)
* [x] `Base.AbstractDisplay`(#31229)
* [x] `Base.AbstractSet` (https://github.com/JuliaLang/julia/pull/31206)
* [x] `Base.Libc.systemsleep` (#31518)
* [x] `Base.Meta.isexpr` (#31246)
* [x] `Base.Meta.quot` (#31246)
* [x] `Base.Meta.show_sexpr` (#31246)
* [x] `Base.SubArray` (#32931)
* [x] `Base.Sys.CPU_NAME` (#31204)
* [x] `Base.Sys.cpu_info` (#31204)
* [x] `Base.Sys.cpu_summary` (#31204)
* [x] `Base.Sys.free_memory` ( #31297)
* [x] `Base.Sys.total_memory` ( #31297)
* [x] `Core` (#31131)
* [x] `Core.Main`
* [x] `Core.Module` (#31131)
* [x] `Core.QuoteNode`
* [x] `Main.Main` (#31131)
* [x] `Base.@MIME_str`
* [x] `Base.@b_str`
* [x] `Base.DEPOT_PATH`
* [x] `Base.Enum`
* [x] `Base.IOStream`
* [x] `Base.MIME`
* [x] `Main.InteractiveUtils`
* [x] `Base.=>` (#27107)
* [x] `Base.@big_str` (#28067)
* [x] `Base.@cmd` (#28062)
* [x] `Base.@int128_str` (#28067)
* [x] `Base.@uint128_str` (#28067)
* [x] `Base.@v_str` (#27107)
* [x] `Base.AbstractVecOrMat` (#27107)
* [x] `Base.Base` (#27107)
* [x] `Base.Broadcast` (#27107)
* [x] `Base.Broadcast.Broadcast` (#27107)
* [x] ~`Base.Broadcast.dotview`~ (not exported)
* [x] `Base.CompositeException` (#28061)
* [x] ~`Base.DFT`~ (deprecated in #21956)
* [x] ~`Base.DFT.DFT`~ (deprecated in #21956)
* [x] `Base.GC` (#27107)
* [x] `Base.GC.GC` (#27107)
* [x] `Base.Inf64` (#27107)
* [x] `Base.NaN64` (#27107)
* [x] ~`Base.Operators`~ (deprecated in #22251)
* [x] ~`Base.Operators.Operators`~ (deprecated in #22251)
* [x] ~`Base.Sys.free_memory`~ (not exported)
* [x] ~`Base.Sys.total_memory`~ (not exported)
* [x] `Base.VecOrMat` (#27107)
* [x] `Base.VersionNumber` (#27107)
* [x] ~`Base.bin`~ (deprecated in #25804)
* [x] ~`Base.dec`~ (deprecated in #25804)
* [x] ~`Base.hex`~ (deprecated in #25804)
* [x] ~`Base.indmax`~ (deprecated to `argmax` in #25654)
* [x] ~`Base.oct`~ (deprecated in #25804)
* [x] `Base.substrides`
* [x] `Base.∉` (#27107)
* [x] `Base.∋` (#27107)
* [x] `Base.∌` (#27107)
* [x] `Base.⊇` (#27107)
* [x] `Base.⊈` (#27107)
* [x] `Base.⊉` (#27107)
* [x] `Base.⊊` (#27107)
* [x] `Base.⊋` (#27107)
* [x] `Main.Base`
* [x] `Base.@big_str`
* [x] `Base.@generated`
* [x] `Base.@int128_str`
* [x] `Base.@uint128_str`
* [x] `Base.AbstractRange` (#28115)
* [x] `Base.AbstractUnitRange` (#28115)
* [x] `Base.CompositeException` (#28061)
* [x] `Base.Cstring` (#28396)
* [x] `Base.Cwstring` (#28396)
* [x] `Base.DenseMatrix` (#28080)
* [x] `Base.DenseVecOrMat` (#28080)
* [x] `Base.DenseVector` (#28080)
* [x] `Base.Dims` (#28080)
* [x] `Base.IndexCartesian` (#28476)
* [x] `Base.IndexLinear` (#28476)
* [x] `Base.InsertionSort` (#28514)
* [x] `Base.LinRange` (#28115)
* [x] `Base.MergeSort` (#28514)
* [x] `Base.OrdinalRange` (#28115)
* [x] `Base.PartialQuickSort` (#28514)
* [x] `Base.QuickSort` (#28514)
* [x] `Base.RawFD` (#28410)
* [x] `Base.Regex`
* [x] `Base.RoundFromZero` (#28427)
* [x] `Base.StepRange` (#28115)
* [x] `Base.StridedArray` (#28144)
* [x] `Base.StridedMatrix` (#28144)
* [x] `Base.StridedVecOrMat` (#28144)
* [x] `Base.StridedVector` (#28144)
* [x] `Base.UnitRange` (#28115)
* [x] ~~`Base.done`~~ (deprecated to `iterate`)
* [x] `Core.DenseArray` (#28080)
* [x] ~~`Main.ans`~~ (special keyword doc)

Edit: updated to remove the entirely-deprecated section

**Comment by JeffBezanson** [comment]
It's not straightforward to add a `@deprecate_binding` for every deprecated function, since the replacement is often non-trivial and/or doesn't have a name.

**Comment by fredrikekre** [comment]
You don't get line numbers for `@deprecate_binding` either, usually just the module, which makes it almost impossible to track down location of where you need to update your code.

**Comment by KristofferC** [comment]
I think 

```
  Base.bin
  Base.dec
  Base.hex
  Base.oct
```

will be unexported after the deprecations are removed?

**Comment by mbauman** [comment]
Those are missing a deprecation in `intfuncs`:

```julia
julia> methods(bin)
# 5 methods for generic function "bin":
…
[2] bin(x::Unsigned, pad::Int64, neg::Bool) in Base at intfuncs.jl:570
...
```

That's why they're getting put in the first list.  Perhaps those methods should be deprecated, too?

**Comment by KristofferC** [comment]
I thought they are just used internally for `string` of a number?

**Comment by mbauman** [comment]
Ah, sure enough.  The script isn't checking `base/exports.jl` — it's just using the method locations as a proxy for entirely deprecated.  I suppose as long as those methods are undocumented that's okay, but it does strike me as a bit of a gray zone.

**Comment by fredrikekre** [comment]
> > In this case, we probably want to @deprecate_binding the binding itself so packages that extend these methods won't be totally surprised when the binding gets removed in 1.0.
>
> You don't get line numbers for @deprecate_binding either, usually just the module, which makes it almost impossible to track down location of where you need to update your code.

Would it be possible to print a warning when extending a totally deprecated function? If so, we can add another argument to `@deprecate`.

**Comment by himanshuladia** [comment]
Hey, I'm a newbie to Julia and want to contribute. Is this something I can help you with?

**Comment by timholy** [comment]
Sure! Just pick something from the list above that doesn't have a check next to it (and verify that it is still undocumented). Or run the `searchdocs` script in the OP.

**Comment by namanbiyani** [comment]
Hi, I was planning to contribute towards GSoC 2019. I want to contribute to this issue. Please give me some guidelines.

**Comment by KristofferC** [comment]
Please don't write the same message in multiple issues. 

This issue is about writing documentation so you would need to get familiar enough with the undocumented things in the first post and then write the actual documentation for them.

**Comment by namanbiyani** [comment]
Please tell me some exports which I should document

**Comment by mbauman** [comment]
I've just updated the checklist.  We're getting very close to closing this issue, so I decided to re-include things that aren't exported directly from `Base` but do get exported by submodules.  Just grab a name and dig in.  Note that the open PR #31131 addresses a few of the items, so don't do those.

**Comment by vtjnash** [comment]
This seems to have stalled, though someone could probably finish it in an afternoon

**Comment by mbauman** [comment]
Superseded by #52725
