### ISSUE TITLE
Making the most of exception stacks

### ISSUE THREAD

**Issue by c42f** [JuliaLang/julia#29792]
Now that #28878 has been merged, let's consider how to make the most of it. Largely, that PR added the exception stack runtime and addressed several bugs in the previous system, but left aside some other possible benefits such as improved error reporting. Here's a list of follow-on features and improvements which have crossed my mind at one time or another.

## Base / stdlib

* [x] Add some convenient way of displaying exception stacks; `showerror` integration, perhaps (#30900)
* [ ] Consider whether `catch_stack()` API types could be improved. For example, returning a custom type rather than a bare `Vector` would allow normal `show` to give something useful here rather than needing a special `showerror` and `display_error`? (#29901)
* [x] Improved error reporting in the REPL with `catch_stack` and `Base.display_error` - figure out how to display all the errors in the stack in a way which emphasizes the information most likely to help fix the problem. (#30900)
* [x] `rethrow(exc)` cleanup: this can become `rethrow()` in nearly all cases now (#29794 https://github.com/JuliaLang/Pkg.jl/pull/873)
* [x] Consider whether the exception nesting behavior of `LoadError` is the right thing. This looks like it might have quite some overlap with the exception stack system for root cause analysis, being in some ways more convenient and some ways less. (#30900)

## Documentation

* [x] Consider whether the manual should discourage `rethrow(exc)`, except in special circumstances. (If the stacks print nicely enough, are there any remaining reasons to use `rethrow(exc)` at all?)

## Runtime

* [ ] `Task` cleanup: Remove `task.backtrace` which now duplicates the storage in `task->excstack` (is this considered a public API? If so, consider getproperty?)
* [ ] Replace panic error dumping (eg, `jl_static_show(JL_STDERR, jl_current_exception())`) with a dump of the full exception stack.
* [ ] `jl_current_exception()` — Asses other uses; consider whether they should be rewritten.
* [ ] Expose full exception stack to embedding API rather than just `previous_exception`?
* [ ] Teach static analyzer about rooting of the return value from `jl_current_exception()` if possible (and add `jl_excstack_t` as a tracked type).  Would be helpful to have #28838 merged first.

@vtjnash

**Comment by vtjnash** [comment]
AFAIK, the necessary and useful bits here are now done, and the issue is no longer useful
