### ISSUE TITLE
Documenting all exports from the standard libraries

### ISSUE THREAD

**Issue by mbauman** [JuliaLang/julia#31202]
Adding docstrings to all exports from Base has been a great success (#26919)!  We are about 80% done there (and I just moved the goalposts — we had been close to 95% prior to that).  That's awesome — thanks everyone who participated.  Now let's move on to the standard libraries!

```julia
searchdocs(mod) = searchdocs!(Any[], mod)
function searchdocs!(objs, mod, seen=Set())
	mod in seen && return
	push!(seen, mod)
	for name in names(mod)
		isdefined(mod, name) || continue
		Base.isdeprecated(mod, name) && continue
		b = getfield(mod, name)
		docs = Base.Docs.doc(Base.Docs.Binding(mod, name))
		if startswith(string(docs), "No documentation found")
		    push!(objs, string(mod, '.', name))
		end
		b isa Module && searchdocs!(objs, b, seen)
	end
	objs
end
ms = []
for M in [filter(f->f[1] in 'A':'Z' && !occursin(r"[-.]", f) && f != "Makefile", readdir("stdlib")); "Pkg"]
    @eval import $(Symbol(M))
    @eval append!(ms, searchdocs($(Symbol(M))))
end
foreach(x->println("* [ ] `", x, '`'), ms)
```

* [x] `Base64.Base64` (#31332)
* [x] `Dates.Apr` (#31218)
* [x] `Dates.April` (#31218)
* [x] `Dates.Aug` (#31218)
* [x] `Dates.August` (#31218)
* [ ] `Dates.DatePeriod`
* [x] `Dates.Dec` (#31218)
* [x] `Dates.December` (#31218)
* [x] `Dates.Feb` (#31218)
* [x] `Dates.February` (#31218)
* [x] `Dates.Fri` (#31574)
* [x] `Dates.Friday` (#31574)
* [x] `Dates.ISODateFormat`
* [x] `Dates.ISODateTimeFormat`
* [x] `Dates.ISOTimeFormat`
* [x] `Dates.Jan`
* [x] `Dates.January`
* [x] `Dates.Jul` (#31218)
* [x] `Dates.July` (#31218)
* [x] `Dates.Jun` (#31218)
* [x] `Dates.June` (#31218)
* [x] `Dates.Mar` (#31218)
* [x] `Dates.March` (#31218)
* [x] `Dates.May` (#31218)
* [x] `Dates.Mon` (#31574)
* [x] `Dates.Monday` (#31574)
* [x] `Dates.Nov` (#31218)
* [x] `Dates.November` (#31218)
* [x] `Dates.Oct` (#31218)
* [x] `Dates.October` (#31218)
* [x] `Dates.RFC1123Format`
* [x] `Dates.Sat` (#31574)
* [x] `Dates.Saturday` (#31574)
* [x] `Dates.Sep` (#31218)
* [x] `Dates.September` (#31218)
* [x] `Dates.Sun` (#31574)
* [x] `Dates.Sunday` (#31574)
* [x] `Dates.Thu` (#31574)
* [x] `Dates.Thursday` (#31574)
* [ ] `Dates.TimePeriod`
* [ ] `Dates.TimeZone`
* [x] `Dates.Tue` (#31574)
* [x] `Dates.Tuesday` (#31574)
* [ ] `Dates.UTC`
* [x] `Dates.Wed` (#31574)
* [x] `Dates.Wednesday` (#31574)
* [ ] `Dates.adjust`
* [x] `Distributed.AbstractWorkerPool` (#31544)
* [x] `Distributed.ClusterManager` (#31234)
* [x] `Distributed.WorkerConfig` (#31234)
* [ ] `Distributed.check_same_host`
* [ ] `FileWatching.FDWatcher`
* [ ] `FileWatching.FileMonitor`
* [ ] `FileWatching.FolderMonitor`
* [ ] `FileWatching.PollingFileWatcher`
* [ ] `InteractiveUtils.InteractiveUtils`
* [x] `Libdl.dllist`
* [x] `Libdl.dlpath`
* [x] `LinearAlgebra.Adjoint` (#31274)
* [x] `LinearAlgebra.BLAS.hemm` (#33801)
* [x] `LinearAlgebra.BLAS.hemm!` (#33801)
* [x] `LinearAlgebra.BLAS.hemv` (#33801)
* [x] `LinearAlgebra.BLAS.hemv!` (#33801)
* [x] `LinearAlgebra.BLAS.her2k` (#33801)
* [x] `LinearAlgebra.BLAS.her2k!` (#33801)
* [x] `LinearAlgebra.BLAS.iamax` (#31277)
* [x] `LinearAlgebra.BLAS.syr2k` (#33801)
* [x] `LinearAlgebra.BLAS.syr2k!` (#33801)
* [x] `LinearAlgebra.BunchKaufman` (#31284)
* [x] `LinearAlgebra.Cholesky` (#31284)
* [x] `LinearAlgebra.CholeskyPivoted` (#31284)
* [x] `LinearAlgebra.Eigen` (#31284)
* [x] `LinearAlgebra.Factorization` (#31284)
* [x] `LinearAlgebra.GeneralizedEigen` (#31284)
* [x] `LinearAlgebra.GeneralizedSVD`  (#31284)
* [x] `LinearAlgebra.GeneralizedSchur` (#31284)
* [x] `LinearAlgebra.Hessenberg`  (#31284)
* [ ] `LinearAlgebra.LAPACKException`
* [x] `LinearAlgebra.LDLt`  (#31284)
* [x] `LinearAlgebra.LQ`  (#31284)
* [x] `LinearAlgebra.LU`  (#31284)
* [x] `LinearAlgebra.PosDefException` (#31251)
* [ ] `LinearAlgebra.RankDeficientException`
* [x] `LinearAlgebra.SVD`  (#31284)
* [x] `LinearAlgebra.Schur`  (#31284)
* [x] `LinearAlgebra.SingularException` (#31251)
* [x] `LinearAlgebra.Transpose` (#31274)
* [x] `LinearAlgebra.UnitLowerTriangular`(#31247)
* [x] `LinearAlgebra.UnitUpperTriangular` (#31247)
* [ ] `LinearAlgebra.copy_transpose!`
* [x] `Logging.Logging` (#31228)
* [ ] `Markdown.@doc_str`
* [ ] `Markdown.@md_str`
* [ ] `Markdown.html`
* [ ] `Markdown.latex`
* [ ] `Printf.Printf`
* [ ] `REPL.AbstractREPL`
* [ ] `REPL.BasicREPL`
* [ ] `REPL.LineEditREPL`
* [ ] `REPL.REPL`
* [ ] `REPL.StreamREPL`
* [x] `Random.AbstractRNG` (#31269)
* [x] `Random.Random`(#31269)
* [ ] `SHA.HMAC_CTX`
* [ ] `SHA.SHA`
* [ ] `SHA.SHA1_CTX`
* [ ] `SHA.SHA224_CTX`
* [ ] `SHA.SHA256_CTX`
* [ ] `SHA.SHA2_224_CTX`
* [ ] `SHA.SHA2_256_CTX`
* [ ] `SHA.SHA2_384_CTX`
* [ ] `SHA.SHA2_512_CTX`
* [ ] `SHA.SHA384_CTX`
* [ ] `SHA.SHA3_224_CTX`
* [ ] `SHA.SHA3_256_CTX`
* [ ] `SHA.SHA3_384_CTX`
* [ ] `SHA.SHA3_512_CTX`
* [ ] `SHA.SHA512_CTX`
* [ ] `SHA.digest!`
* [ ] `SHA.hmac_sha1`
* [ ] `SHA.hmac_sha224`
* [ ] `SHA.hmac_sha256`
* [ ] `SHA.hmac_sha2_224`
* [ ] `SHA.hmac_sha2_256`
* [ ] `SHA.hmac_sha2_384`
* [ ] `SHA.hmac_sha2_512`
* [ ] `SHA.hmac_sha384`
* [ ] `SHA.hmac_sha3_224`
* [ ] `SHA.hmac_sha3_256`
* [ ] `SHA.hmac_sha3_384`
* [ ] `SHA.hmac_sha3_512`
* [ ] `SHA.hmac_sha512`
* [ ] `SHA.sha1`
* [ ] `SHA.sha224`
* [ ] `SHA.sha256`
* [ ] `SHA.sha2_224`
* [ ] `SHA.sha2_256`
* [ ] `SHA.sha2_384`
* [ ] `SHA.sha2_512`
* [ ] `SHA.sha384`
* [ ] `SHA.sha3_224`
* [ ] `SHA.sha3_256`
* [ ] `SHA.sha3_384`
* [ ] `SHA.sha3_512`
* [ ] `SHA.sha512`
* [ ] `SHA.update!`
* [ ] `Serialization.AbstractSerializer`
* [ ] `Serialization.Serializer`
* [x] `SharedArrays.SharedMatrix` (#31263)
* [x] `SharedArrays.SharedVector` (#31263)
* [x] `Sockets.@ip_str` (#31225)
* [x] `Sockets.IPAddr` (#31225)
* [x] `Sockets.Sockets` (#31225)
* [x] `SparseArrays.AbstractSparseArray` (#31286)
* [x] `SparseArrays.AbstractSparseMatrix` (#31286)
* [x] `SparseArrays.AbstractSparseVector` (#31286)
* [x] `SparseArrays.droptol!` (#31286)
* [ ] `SuiteSparse.SuiteSparse`
* [x] `UUIDs.UUIDs` (#33791)
* [ ] `Unicode.Unicode`
* [ ] `Pkg.@pkg_str`
* [ ] `Pkg.PKGMODE_MANIFEST`
* [ ] `Pkg.PKGMODE_PROJECT`
* [ ] `Pkg.Pkg`
* [ ] `Pkg.Registry`
* [ ] `Pkg.Registry.Registry`
* [ ] `Pkg.UPLEVEL_MAJOR`
* [ ] `Pkg.UPLEVEL_MINOR`
* [ ] `Pkg.UPLEVEL_PATCH`

**Comment by dkarrasch** [comment]
@mbauman or @kshyatt, could you please mark those commands which are covered by PRs? It should be the twelve month constants and there abbreviations (#31218), the four `SparseArrays.XYZ` (#31286), and all factorization docstrings (#31284). Just to avoid redundant work as has happened already. Many thanks!

**Comment by asinghvi17** [comment]
Shouldn't the Markdown types also be documented, since they have constructors?

**Comment by mbauman** [comment]
This list is only enumerating the exported names — those are the official public (and stable) APIs and are the biggest priorities.

**Comment by KristofferC** [comment]
> Shouldn't the Markdown types also be documented, since they have constructors?

It is also very questionable if the Markdown stuff is considered public. And if not, I don't think we want to make it public by documenting it + putting it in the manual. It doesn't feel up to snuff in terms of robustness and quality that we want.

**Comment by vtjnash** [comment]
There's been a lot of progress. Someone could probably finish this list in an afternoon:
 - [ ] `Dates.adjust`
 - [ ] `Distributed.check_same_host`
 - [ ] `FileWatching.FDWatcher`
 - [ ] `FileWatching.FileMonitor`
 - [ ] `FileWatching.FolderMonitor`
 - [ ] `FileWatching.PollingFileWatcher`
 - [ ] `LinearAlgebra.LAPACKException`
 - [ ] `LinearAlgebra.RankDeficientException`
 - [ ] `LinearAlgebra.copy_transpose!`
 - [ ] `Markdown.@doc_str`
 - [ ] `Markdown.@md_str`
 - [ ] `Markdown.html`
 - [ ] `Markdown.latex`
 - [ ] `Pkg.@pkg_str`
 - [ ] `Pkg.PKGMODE_MANIFEST`
 - [ ] `Pkg.PKGMODE_PROJECT`
 - [ ] `Pkg.PRESERVE_ALL`
 - [ ] `Pkg.PRESERVE_DIRECT`
 - [ ] `Pkg.PRESERVE_NONE`
 - [ ] `Pkg.PRESERVE_SEMVER`
 - [ ] `Pkg.PRESERVE_TIERED`
 - [ ] `Pkg.PreserveLevel`
 - [ ] `Pkg.UPLEVEL_MAJOR`
 - [ ] `Pkg.UPLEVEL_MINOR`
 - [ ] `Pkg.UPLEVEL_PATCH`
 - [ ] `REPL.AbstractREPL`
 - [ ] `REPL.BasicREPL`
 - [ ] `REPL.LineEditREPL`
 - [ ] `REPL.StreamREPL`
 - [ ] `SHA.HMAC_CTX`
 - [ ] `SHA.hmac_sha1`
 - [ ] `SHA.hmac_sha224`
 - [ ] `SHA.hmac_sha256`
 - [ ] `SHA.hmac_sha2_224`
 - [ ] `SHA.hmac_sha2_256`
 - [ ] `SHA.hmac_sha2_384`
 - [ ] `SHA.hmac_sha2_512`
 - [ ] `SHA.hmac_sha384`
 - [ ] `SHA.hmac_sha3_224`
 - [ ] `SHA.hmac_sha3_256`
 - [ ] `SHA.hmac_sha3_384`
 - [ ] `SHA.hmac_sha3_512`
 - [ ] `SHA.hmac_sha512`
 - [ ] `Serialization.AbstractSerializer`
 - [ ] `Serialization.Serializer`
 
Though the jll libraries are new, they can be ignored:

 - [ ] `CompilerSupportLibraries_jll.libgfortran`
 - [ ] `CompilerSupportLibraries_jll.libgomp`
 - [ ] `CompilerSupportLibraries_jll.libstdcxx`
 - [ ] `GMP_jll.libgmp`
 - [ ] `GMP_jll.libgmpxx`
 - [ ] `LLVMLibUnwind_jll.llvmlibunwind`
 - [ ] `LibCURL_jll.libcurl`
 - [ ] `LibGit2_jll.libgit2`
 - [ ] `LibSSH2_jll.libssh2`
 - [ ] `LibUV_jll.libuv`
 - [ ] `LibUnwind_jll.libunwind`
 - [ ] `MPFR_jll.libmpfr`
 - [ ] `MbedTLS_jll.libmbedcrypto`
 - [ ] `MbedTLS_jll.libmbedtls`
 - [ ] `MbedTLS_jll.libmbedx509`
 - [ ] `OpenBLAS_jll.libopenblas`
 - [ ] `OpenLibm_jll.libopenlibm`
 - [ ] `PCRE2_jll.libpcre2_8`
 - [ ] `SuiteSparse_jll.libamd`
 - [ ] `SuiteSparse_jll.libbtf`
 - [ ] `SuiteSparse_jll.libcamd`
 - [ ] `SuiteSparse_jll.libccolamd`
 - [ ] `SuiteSparse_jll.libcholmod`
 - [ ] `SuiteSparse_jll.libcolamd`
 - [ ] `SuiteSparse_jll.libklu`
 - [ ] `SuiteSparse_jll.libldl`
 - [ ] `SuiteSparse_jll.librbio`
 - [ ] `SuiteSparse_jll.libspqr`
 - [ ] `SuiteSparse_jll.libsuitesparse_wrapper`
 - [ ] `SuiteSparse_jll.libsuitesparseconfig`
 - [ ] `SuiteSparse_jll.libumfpack`
 - [ ] `Zlib_jll.libz`

**Comment by nsajko** [comment]
Related issues: #19529, #51335.

**Comment by mbauman** [comment]
Superseded by #52725
