### ISSUE TITLE
Sanitizer enablement tracking issue

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#46349]
This is an issue for everything that needs to happen, so we can start regularly using the sanitizers, both on CI and elsewhere. It's quite a bit, requires some coordination and I don't want to forget everything, so a long checklist it is.

- [ ] Merge #46322 or #46260 to fix asan complaint in generated code
- [ ] Merge #46336
- [ ] Enable asan on CI
    - [ ] One CI job every commit running read/channels/spawn
    - [ ] One nightly job running full bootstrap + testsuite
 - [ ] Finish and merge #46348
 - [ ] Merge https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/255 and deploy on Yggdrasil
 - [ ] Have julia detect its sanitizer status and add platform tags
 - [ ] Patch our dependencies to add __msan_unpoison around asm code
 - [ ] Merge https://github.com/JuliaPackaging/Yggdrasil/pull/5308 to get msan-enabled libstdcxx
 - [ ] Merge https://github.com/JuliaPackaging/Yggdrasil/pull/5311 to get an msan-capable fortran compiler
 - [ ] Build `-sanitizer` versions of all our dependencies
 - [ ] Set up msan CI
 - [ ] [Optional] Make sanitizers more precise around our GC allocations.
 - [ ] [Optional] Add a way to build sanitizer-enabled sysimages from non-sanitizer builds

**Comment by gbaraldi** [comment]
What about TSAN, not sure if it's going to help anywhere, but it looks like we currently just build the julia runtime with it, nothing more.

**Comment by Keno** [comment]
> What about TSAN, not sure if it's going to help anywhere, but it looks like we currently just build the julia runtime with it, nothing more.

I think tsan is mostly working, but I haven't played with it extensively yet. For now, the target here it get asan/msan working well to hopefully stop memory issues in external libraries from breaking CI as frequently as they have been.

**Comment by gbaraldi** [comment]
What I meant is that we should do something with it. I believe we just build the runtime for now and maybe we should run at least the Threads testset with it on.

**Comment by gbaraldi** [comment]
Deps to build:
- [x] GMP
- [ ] LLVMLibUnwind
- [ ] LibCurl
- [ ] LibGit2
- [ ] LibSSH2
- [ ] LibUV
- [ ] LibUnwind
- [ ] MbedTLS
- [ ] PCRE2
- [ ] OpenLibm
- [ ] SuiteSparse
- [ ] libblastrampoline
- [ ] nghttp2
- [ ] p7zip

**Comment by gbaraldi** [comment]
Using the PR, which kind of works I've been compiling a couple of failures. The atomic failure seems to be related to padding, and a MWE is 
```julia
mutable struct ARefxy{T}
    @atomic x::T
    y::T
end

struct PadIntA <: Number # internal padding
    a::Int8
    b::Int16
end

r = ARefxy{PadIntA}(PadIntA(15,12), PadIntA(15,12))
replacefield!(r, :x, PadIntA(15,11), PadIntA(15,12), :sequentially_consistent, :sequentially_consistent)
```
I'm not sure what the correct thing here is, maybe we should just unpoison it since we know we are moving padding around.
