### ISSUE TITLE
missing cbrt(A::AbstractMatrix)

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#47513]
I just noticed that this function is missing, even though we have `sqrt(A)` and `A^(1/3)` for matrices.

Seems like it should be ~~straightforward and~~ reasonable to add.

`cbrt(A::AbstractMatrix) = A^(1//3)` ~~may be~~ is definitely insufficient, however: we should at least have a specialized `cbrt(A::AbstractMatrix{<:Real})` method that always returns a type-stable real matrix.

[This paper](https://www.sciencedirect.com/science/article/pii/002437958380010X?via%3Dihub) (which we use for `sqrt(A)`) also gives a matrix `cbrt` algorithm (that yields a real root if you use `cbrt` in equation 5.2) for the non-real-symmetric case.  (The real-symmetric case is easy because you just apply `cbrt` to the eigenvalues.)

**Comment by matrixbot123** [comment]
Hey , I want to contribute and try to  write code for cbrt() function of matrix. But I am new to  contributing to julia and concept of cube root of a matrix. Can you please elaborate this point
> cbrt(A::AbstractMatrix) = A^(1//3) may be insufficient, however: we should at least have a specialized cbrt(A::AbstractMatrix{<:Real}) method that always returns a type-stable real matrix.

**Comment by stevengj** [comment]
For `realmatrix^rational` powers, in general it's problematic to have a [type stable](https://docs.julialang.org/en/v1/manual/performance-tips/#Write-%22type-stable%22-functions) function, because it may produce real or complex outputs depending on the *values* (not just types) of the matrix and the exponent.

However, the `cbrt` function is nicer, because we know (at compile-time) that we are computing the `1/3` power, which always has a real output for real inputs.

**Comment by stevengj** [comment]
Related to #36534 — the question of which branch cut should be used is non-obvious even for `cbrt(::Complex)`.  For `cbrt(::Matrix{<:Real})` it seems like it would be nice to have the real result.

**Comment by stevengj** [comment]
Consistent with the discussion in #36534, I think we would *only* want to define this for real matrices.

**Comment by oscardssmith** [comment]
look for where sqrt of matrix is defined. next to that seems like a good place.

**Comment by aravindh-krishnamoorthy** [comment]
@theWiseAman Kindly let me know if I can be of help with this implementation...

**Comment by stevengj** [comment]
This is not such an easy issue to work on unless you understand a fair amount of linear algebra.   In particular, until you understand why `sqrt(A)` can't use eigenvalues for non-Hermitian matrices, and what it does instead, you won't understand this issue.

At *minimum*, you need to understand [this paper](https://www.sciencedirect.com/science/article/pii/002437958380010X?via%3Dihub) and [this code for `sqrt(A)`](https://github.com/JuliaLang/julia/blob/0da46e25c865a390b5c2de20c2d40afb41fcac0a/stdlib/LinearAlgebra/src/dense.jl#L877-L903) and [this code for `A^p`](https://github.com/JuliaLang/julia/blob/0da46e25c865a390b5c2de20c2d40afb41fcac0a/stdlib/LinearAlgebra/src/dense.jl#L490-L521) before you can sensibly work on `cbrt(A)`.

**Comment by aravindh-krishnamoorthy** [comment]
> This is not such an easy issue to work on unless you understand a fair amount of linear algebra. In particular, until you understand why `sqrt(A)` can't use eigenvalues for non-Hermitian matrices, and what it does instead, you won't understand this issue.
> 
> At _minimum_, you need to understand [this paper](https://www.sciencedirect.com/science/article/pii/002437958380010X?via%3Dihub) (which also gives a `cbrt` algorithm!) and [this code for `sqrt(A)`](https://github.com/JuliaLang/julia/blob/0da46e25c865a390b5c2de20c2d40afb41fcac0a/stdlib/LinearAlgebra/src/dense.jl#L877-L903) and probably [this code for `A^p` too](https://github.com/JuliaLang/julia/blob/0da46e25c865a390b5c2de20c2d40afb41fcac0a/stdlib/LinearAlgebra/src/dense.jl#L490-L521) before you can sensibly work on `cbrt(A)`.

Hello @stevengj, thank you for this valuable input. I have taken a look at the mentioned references: I'm aware of the paper [1] and I also reviewed the code for `sqrt(A)` and `A^p`. However, I'm not sure if I fully appreciate the hurdles you allude to in the post. I kindly request you to review my plan below and let me know if I've missed something.

1. Straightforward implementations to begin with the task:
1.1 Diagonal matrices: `cbrt :: Diagonal{T<:Union{Real,Complex}} -> Diagonal{T}`, can be made type stable.
1.2 Symmetric matrices: `cbrt :: Symmetric{T<:Real} -> Symmetric{T<:Real}`, can be made type stable.
1.3 Hermitian-symmetric matrices: `cbrt :: Hermitian{T<:Complex} -> Hermitian{T<:Complex}`, type stable. 

2. Arbitrary complex-valued matrices:
2.1 Using Schur decomposition: `cbrt :: AbstractMatrix{T<:Complex} -> AbstractMatrix{T<:Complex}`, type stable.
2.2 [OPEN] Literature survey for algorithms for cube roots of triangular matrices from 1983 -- 2023.
2.3 Known option (1983): Also as you mention, a method is provided in [1, Section 5] using similar principles as the square-root method.

3. Arbitrary real-valued matrices:
3.1 Using Schur decomposition: `cbrt :: AbstractMatrix{T1<:Real} -> AbstractMatrix{T2}`. Outputs of Schur decomposition are: (a) triangular for matrices with real-valued eigenvalues, and (b) quasi-triangular for matrices with complex-valued eigenvalues.
3.2 For matrices with real-valued eigenvalues, utilise a real-valued version of the algorithm in Step 2 above. In this case, the output matrix is real-valued.
3.3 **[APPROACH 1]** For matrices with complex-valued eigenvalues, convert the quasi-triangular output to complex-valued triangular via Given's rotations, see `function Schur{CT}(S::Schur{<:Real}) where {CT<:Complex}` in `schur.jl`, and utilise the algorithm in Step 2 for complex-valued matrices. This approach is **type unstable** since the output matrix is complex-valued.
3.4 **[APPROACH 2]** For matrices with complex-valued eigenvalues, implement a cube-root function for a quasi-triangular matrix, which can be adapted to return real-valued results. This approach is type stable since the output matrix is real-valued. However, a quick search revealed no cube root algorithms for quasi-triangular (2x2 blocks on the diagonal) matrices. An algorithm can surely be developed but might take some time to get right.
3.5 **[APPROACH 3, Not elegant at all!]** For matrices with complex-valued eigenvalues, return an error and force the user to wrap the matrix in `complex`, see the first inconsistency below. This approach is type stable.

[1] Åke Björck, Sven Hammarling, A Schur method for the square root of a matrix, Linear Algebra and its Applications, Volumes 52–53, 1983, Pages 127-140, ISSN 0024-3795, https://doi.org/10.1016/0024-3795(83)80010-X.

Lastly, while reviewing the code, I found a few inconsistencies:

1. `sqrt` behaviour is non-intuitive. Consider:
```julia
julia> using LinearAlgebra
julia> sqrt(Diagonal([-1. 0; 0 1.]))
ERROR: DomainError with -1.0:
sqrt was called with a negative real argument but will only [...]
```
but

```julia
julia> sqrt([-1. 0; 0 1.])
2×2 Matrix{ComplexF64}:
 0.0+1.0im  0.0+0.0im
 0.0+0.0im  1.0+0.0im
```
(Note: There are several other inconsistencies. I'll just stop here.)

2. `sqrt` dies silently for rank-deficient matrices:
```julia
julia> using LinearAlgebra
julia> sqrt([0 1; 0 0])
2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0
```
Perhaps showing a warning or an error would be better here.

**Comment by stevengj** [comment]
> Arbitrary complex-valued matrices

As discussed above, I wouldn't support complex matrices, because it relies on nonstandard branch cuts that will be different from `A^(1//3)`.   The point of `cbrt(A)` is to give a real cube root for real matrices.   Basically, you want to do:

1. For real-symmetric values, use `cbrt` of the eigenvalues.
2. For arbitrary real matrices, use the Schur-based algorithm referenced in the paper.  You don't want to use eigenvalues because the eigenvectors may be ill-conditioned.

If you have problems with `sqrt`, please file a separate issue.

**Comment by aravindh-krishnamoorthy** [comment]
Based on my revised reading of the requirements of this issue, taking into consideration the latest post by the author (@stevengj), please find below a summary of the goal of this issue and a plan.

# Goal
Akin to scalar values, cube-root of a real-valued matrix can be arranged to be real-valued. In Julia, presently, cube-root of a matrix via `A^(1//3)` is not guaranteed to return real-valued outputs for real-valued inputs. Hence, the goals of this issue are as follows:
1. Provide a function `cbrt :: AbstractMatrix{<:Real} -> AbstractMatrix{<:Real}`, which provides real-valued outputs for real-valued inputs.
2. On the other hand, this issue is not concerned with `cbrt :: AbstractMatrix{<:Complex} -> AbstractMatrix{<:Complex}`, which can just be delegated to `A^(1//3)`, as indicated in the issue text.

# Plan
## 1. Diagonal, symmetric, and Hermitian matrices
- [ ] Diagonal matrices: `cbrt :: Diagonal{T<:Real} -> Diagonal{T}`, can be made type stable.
- [ ] Symmetric matrices: `cbrt :: Symmetric{T<:Real} -> Symmetric{T}`, can be made type stable.
- [ ] Hermitian-symmetric matrices: `cbrt :: Hermitian{T<:Complex} -> Hermitian{T<:Complex}`, delegate to `A^(1//3)`.

### Implementation notes
As indicated above by the OP, the scalar `cbrt` function returns real-valued outputs for real-valued inputs. Hence, the implementations of Point 1. above can be based on `cbrt` of the diagonal or eigenvalues. 

**TODO:**
- [ ] Benchmark `eigen` and `schur` based implementations for symmetric and Hermitian matrices as a function of the matrix dimension to identify the most efficient implementation.

## 2. Arbitrary complex-valued matrices:
- [ ] Abstract matrices: `cbrt :: AbstractMatrix{T<:Complex} -> AbstractMatrix{T}`, type stable, delegated to `A^(1//3)`.

## 3. Arbitrary real-valued matrices:
- [ ] Abstract matrices: `cbrt :: AbstractMatrix{T<:Real} -> AbstractMatrix{T}`, can be made type stable.

### Implementation notes
Except for the algorithm indicated by OP in [1], a quick search revealed no literature from $1983 - 2023$ for a real-valued to real-valued cube root of matrices. Schur-decomposition based implementation is preferred here as, unlike `eigen`, `schur` can handle defective matrices. However, Schur-based implementation necessitates finding the cube-root of a quasi-triangular matrix, which might be cumbersome.

**Preparation:**
- [ ] Review the cube root algorithm in [1] in detail and **extend the method for quasi-triangular matrices**, which are are obtained for input matrices with complex eigenvalues.
- [ ] Review literature in the period $1983 - 2023$ for applicable algorithms.

# Overall TODOs
- [ ] Ensure graceful handling of rank-deficient matrices (error or warning messages).

[1] Åke Björck, Sven Hammarling, A Schur method for the square root of a matrix, Linear Algebra and its Applications, Volumes 52–53, 1983, Pages 127-140, ISSN 0024-3795, https://doi.org/10.1016/0024-3795(83)80010-X.

**Comment by stevengj** [comment]
> Benchmark eigen and schur based implementations for symmetric and Hermitian matrices as a function of the matrix dimension to identify the most efficient implementation.

For real-symmetric matrices, you should definitely use the `eigen` algorithm.  (Similar to matrix powers.)

**Comment by cafaxo** [comment]
This paper has an algorithm for computing p-th real roots from the quasi-triangular Schur decomposition:
Smith, M. I. (2003). A Schur Algorithm for Computing Matrix pth Roots. In SIAM Journal on Matrix Analysis and Applications (Vol. 24, Issue 4, pp. 971–989). Society for Industrial & Applied Mathematics (SIAM). https://doi.org/10.1137/s0895479801392697

**Comment by aravindh-krishnamoorthy** [comment]
# Implementation <span>#</span>1
- Based on reference [2] to gain a first understanding of the complexity involved. Draft code, but comments and suggestions are welcome. 
- Warning ⚠️: [Development branch](https://github.com/aravindh-krishnamoorthy/julia/tree/cbrt) may have force pushes!

[2] Smith, M. I. (2003). A Schur Algorithm for Computing Matrix pth Roots. In SIAM Journal on Matrix Analysis and Applications (Vol. 24, Issue 4, pp. 971–989). https://doi.org/10.1137/s0895479801392697

- [X] `U22!`: Cube root of a 2x2 real-valued matrix with complex conjugate eigenvalues. [Permalink to method.](https://github.com/aravindh-krishnamoorthy/julia/blob/43c3dba85db02c31dfe4e5e7c45373e811261a39/stdlib/LinearAlgebra/src/dense.jl#L1697)
- [ ] Cube root of a block diagonal matrix (mainly identification of $1\times1$ and $2\times2$ blocks).-- first step of Algorithm 4.3 in [2].
- [ ] Remainder of Algorithm 4.3 in [2]; steps TBD.
