### ISSUE TITLE
Move parallel precompile out of Pkg

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#49433]
Parallel precompile is pretty much independent of Pkg. As Pkg is getting moved out of the sysimage it becomes awkward to have it there. For example, you still want parallel precompile for package load even if you haven't loaded Pkg in the session. And issues like https://github.com/JuliaLang/Pkg.jl/issues/3442 also shows it is awkward to have to load Pkg in various environment just to get access to the precompilation feature. 
```[tasklist]
### Tasks
- [ ] https://github.com/JuliaLang/Pkg.jl/pull/3573
- [ ] https://github.com/JuliaLang/Pkg.jl/issues/3488
- [ ] https://github.com/JuliaLang/Pkg.jl/issues/3548
- [ ] https://github.com/JuliaLang/Pkg.jl/issues/3487
- [ ] https://github.com/JuliaLang/Pkg.jl/issues/2648
- [ ] https://github.com/JuliaLang/Pkg.jl/issues/3068
- [ ] https://github.com/JuliaLang/Pkg.jl/pull/3582
- [ ] https://github.com/JuliaLang/Pkg.jl/issues/3637
```

**Comment by IanButterworth** [comment]
Once the code is moved over to Base it's going to be pretty difficult to maintain a version in Pkg on 1.10 (which looks likely to become an LTS) and 1.11+ in Base, so I've added all the filed issues that I think should be ideally dealt with before moving it over.

The list doesn't have to be completely done, it just makes it easier to do the more are.

**Comment by IanButterworth** [comment]
One thing to bear in mind with this is that `Pkg.precompile` does extra Pkg things before precompiling if necessary, like resolve and instantiate. Once the parallel precompilation mechanic is in Base, if we wanted to avoid using Pkg in the code load precompilation path, there would need to be graceful errors if the environment isn't resolved or instantiated, telling the user to use Pkg to do that. That might be a bit of a UX regression.

**Comment by KristofferC** [comment]
This is done.
