### ISSUE TITLE
Transition to JITLink

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/julia#50248]
In discussion with @gbaraldi I thought it good to write down what needs to happen for us to fully transition to JITLink and remove RTDyld support

```[tasklist]
### Upstream Tasks
- [x] COFF/Windows support, as far as I know landed in LLVM 15
- [ ] PPC support, skeleton landed in https://reviews.llvm.org/D148192
- [ ] Profiling support https://github.com/llvm/llvm-project/issues/30869
- [ ] Reduce memory mappings https://github.com/llvm/llvm-project/issues/63236
```

```[tasklist]
### Tasks
- [ ] Enable COFF support
- [ ] Backport perf listeners to our source tree if possible
```

**Comment by weliveindetail** [comment]
Which other architectures need COFF support? PPC? AArch64?

**Comment by vchuravy** [comment]
Since COFF is a Windows only format, I suppose COFF/arm64 might be interesting eventually.
