### ISSUE TITLE
Improve reuse of `/compiled` cache in CI

### ISSUE THREAD

**Issue by IanButterworth** [JuliaLang/julia#50667]
It would be nice to speed up julia CI startup time

Take GitHub julia CI, which typically 
- downloads any registries
- downloads packages
- downloads any artifacts
- builds all packages
- precompiles all packages with test args (--coverage and --check-bounds etc.)
- runs tests

https://github.com/julia-actions/cache provides a way to cache useful parts of the depot between runs.

However two of the above are disabled by default: 
- `/registries` which seems the path is clear to that being enabled now https://github.com/julia-actions/cache/pull/62
- `/compiled` which means all packages are precompiled each run.

I tried enabling caching of `/compiled` over at https://github.com/JuliaIO/PNGFiles.jl/pull/66

However on the second run it hits re-precompilation for most of the packages because:
1. pkgimages are disabled in the test environment due to coverage being on by default on `julia-runtest` 
2. We only ship julia with stdlib caches with pkgimages on (default and `--check-bounds=yes`)

i.e.
```
 Debug: Rejecting cache file /opt/hostedtoolcache/julia/1.9.2/x64/share/julia/compiled/v1.9/MbedTLS_jll/u5NEn_RmBmg.ji for  [top-level] since the flags are mismatched
│   current session: use_pkgimages = false, debug_level = 1, check_bounds = 1, inline = true, opt_level = 2
│   cache file:      use_pkgimages = true, debug_level = 1, check_bounds = 1, inline = true, opt_level = 2
└ @ Base loading.jl:2730
```

Two ways to improve this caching would be to
- Enable pkgimages in more CI because coverage being on by default means no pkgimages - https://github.com/JuliaLang/julia/pull/48183 which I stalled on. Help appreciated
- Include `pkgimage=no` caches for stdlibs https://github.com/JuliaLang/julia/pull/50666

```[tasklist]
### Tasks
- [ ] https://github.com/JuliaLang/julia/issues/50918
- [ ] https://github.com/JuliaLang/julia/pull/49866
- [ ] https://github.com/JuliaLang/julia/pull/50666
- [ ] https://github.com/JuliaLang/julia/pull/52123
- [ ] https://github.com/julia-actions/cache/pull/71
- [ ] https://github.com/julia-actions/julia-runtest/issues/89
- [ ] https://github.com/julia-actions/julia-buildpkg/issues/40
- [ ] https://github.com/julia-actions/setup-julia/pull/196
```

**Comment by IanButterworth** [comment]
Also, if both `/registries` and `/compiled` become default on, https://github.com/julia-actions/cache becomes quite powerful so https://github.com/julia-actions/julia-runtest could be trained to suggest the cache action if it sees that a depot doesn't exist yet.

**Comment by IanButterworth** [comment]
Now that https://github.com/JuliaLang/julia/pull/52123 is merged we're able to see the effect of caching `/compiled` over at https://github.com/julia-actions/cache/pull/71

For an install and load-only CI run, 1.11 goes from 2 minutes to 40s.

**Comment by IanButterworth** [comment]
[v1.9.5 of julia-actions/setup-julia](https://github.com/julia-actions/setup-julia/releases/tag/v1.9.5) fixes this now for all julia versions, by maintaining the mtime of the julia source files from the archives.

You can see that in this run no platform re-precompiled anything but the checked out package https://github.com/IanButterworth/PowerMonitor.jl/actions/runs/7425482162/job/20207208161

The only remaining things to do is to get more CI to use `julia-actions/cache` which I'm proposing by getting other actions to notify if caching isn't detected
- https://github.com/julia-actions/julia-runtest/issues/89
- https://github.com/julia-actions/julia-buildpkg/issues/40

But this is now just an adoption issue, so I think we can close this
