### ISSUE TITLE
Meta-issue for improving the REPL experience

### ISSUE THREAD

**Issue by tecosaur** [JuliaLang/julia#50817]
I've ended up on a path to improve the REPL experience in a few ways, and thought I'd actually write up the overall plan.

- [x] Wait for JuliaSyntax to be merged #46372
- [ ] Get StyledStrings capabilities into Base #49586
  - [ ] Prerequisite: #50797
  - [ ] Write docs, tests, ...
- [ ] Revamp TerminalMenus #48381
- [ ] Util for highlighting Julia code (steal from my Replete.jl project)
  - Can be applied to: Markdown code blocks, history selection, REPL itself
- [ ] Improved history selection (also from my Replete.jl project)
  - [ ] Reimplement with some nicer abstractions, get vertical completion/selection for free along the way
- [ ] Investigate in-REPL syntax highlighting

**Comment by c42f** [comment]
I am so onboard with this plan!  Not confident how much I can promise to work on the code directly, but I'm happy to support via `JuliaSyntax` adjustments and advice as/if necessary.

Because `REPL` is a stdlib, I think you can feel free to use the the JuliaSyntax API (directly, not only via `Meta.parse()`) and I hope that should make REPL syntax highlighting fairly easy once we've got Styled strings merged. A nice side effect of this should somehow be syntax highlighting of broken syntax within the REPL as people type. So people can fix that syntax as they type rather than trying to eval it first.  OhMyREPL already has some of this via the JuliaSyntax parser, but it's still based on tokens rather than the parse tree so some of that info goes missing along the way.

Maybe we can add another item to the list:

* Reimplement REPL completion based on the JuliaSyntax parser.

Because last time I looked at the REPL.jl completion code it's ... a bit of a scary disaster area of regexes and heuristics IIUC

**Comment by c42f** [comment]
Another item to add to the list:

* Make the REPL an external (upgradable) stdlib. I suspect this would greatly improve our ability to make progress. See https://github.com/JuliaLang/julia/issues/50697

**Comment by tecosaur** [comment]
I'm wondering, would it be worth making a channel on Zulip/etc. for chatting about this? I think it could be worth making a space for discussion around this, and I'm not sure that just this issue suffices.

**Comment by caleb-allen** [comment]
@tecosaur I think that's a good idea. I was surprised that a #repl channel doesn't already exist in the Slack

**Comment by tecosaur** [comment]
Personally, I'm much more a fan of the Zulip, so if other people are fine with that (yes?), I'll put in a request for a #repl channel there.

**Comment by tecosaur** [comment]
I've now made a Zulip stream: https://julialang.zulipchat.com/#narrow/stream/404905-repl :slightly_smiling_face:

**Comment by tecosaur** [comment]
FYI, there is now also [a Slack channel](https://julialang.slack.com/archives/C060R496FH9) (that currently basically says "go to Zulip"), and the Slack/Zulip channels should be listed as part of the new "REPL working group" soon (with me as the contact).

Meetings etc. TBD, but for now I thought it would be a nice start to better collect people interested in driving this aspect of the Julia experience forward :slightly_smiling_face:.

**Comment by tecosaur** [comment]
I've added a plot to the end of the initial message that people subscribed to this issue may find of interest, I've also plopped it in a zulip thread.

**Comment by tecosaur** [comment]
From slack, Ruby's interactive REPL has had a fun update that we might want to look at in this effort: https://railsatscale.com/2023-12-19-irb-for-ruby-3-3/

**Comment by tecosaur** [comment]
I'm starting an effort to provide a fresh take on `REPL.TerminalMenus`, see the Zulip thread for more info: [#repl Developing InteractivePrompts.jl](https://julialang.zulipchat.com/#narrow/stream/404905-repl/topic/Developing.20InteractivePrompts.2Ejl/near/419771104).
