### ISSUE TITLE
Roadmap: basic linear algebra framework for generic eltypes

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#5429]
This issue continues on from #3014 and #5381 as a placeholder to track what is left to put into place a useful skeleton of basic linear algebra for generic element types.

Routines for special matrices (#3688)
- [x] `Tridiagonal` linear solver (#39701)
- [ ] `Tridiagonal eigensystem solver (@andreasnoack mentioned he had some code for this?)  

`Factorization`s
- [x] LL' Cholesky
- [x] pivoted LU 
- [x] QR
  - Should we just pick one of: modified Gram-Schmidt, Givens and Householder algorithms?
  - Want both the basic and pivoted (rank-revealing) variants?
- [ ] SVD
- [ ] Check that with the necessary factorizations in place, that `inv` and `eig` work.

**Comment by simonbyrne** [comment]
Code for generic SVD is available in [GenericSVD.jl](https://github.com/simonbyrne/GenericSVD.jl). Do we want to polish this up and merge into Base?

**Comment by ViralBShah** [comment]
Yes, that sounds like a good idea.

**Comment by 0joshuaolson1** [comment]
Here's one more vote for arbitrary-precision `eig` (`eigvals`).

**Comment by andreasnoack** [comment]
@0joshuaolson1 Some of this work has been done in https://github.com/andreasnoack/LinearAlgebra.jl but it still needs to be better tested.

**Comment by stevengj** [comment]
Some of this functionality has been implemented to packages, e.g. https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl … I suspect that we should close this issue in favor of more specific issues or packages?
