### ISSUE TITLE
Towards array nirvana

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#7941]
For 0.4 several of us want to see significant improvements in arrays. I'm opening this meta-issue to help organize the effort. I'll be brief here and link out to issues/packages for more detailed explanations. Please add to these bullet points.

##### Underlying technologies
The first two are essential, the third is nearly essential.
- [ ] Julia native bounds checking and removal (#7799) (PR: #8227)
- [x] Staged functions (#7474, splatting fixes #7935)
- [x] Efficient cartesian iteration ~~(#6437)~~ (#8432)
- [ ] Eliminate the performance hit from splatting (update: `stagedfunctions` can be coaxed into doing this for you)
- [x] Even more efficient tuple storage (for implementing fixed-size arrays)
- [ ] A mutable fixed-size buffer type analogous to tuples? (for mutable fixed-size arrays; Clang.jl would probably like this too)
- [x] Make `[a, b]` non-concatenating #3737/#2488

I'm guessing the approach for implementing #7799 will also allow one to specify manual inlining (which is where the idea was originally proposed), which is the main bottleneck for #6437. So that's almost a 2-for-1 deal.

##### Implementation
The first two are essential.
 - [x] [ArrayViews](https://github.com/lindahua/ArrayViews.jl) (#5556). ~~In my opinion, we likely just want the `ContiguousView` part of it.~~
 - [x] Work in progress: https://github.com/timholy/ArrayViewsAPL.jl
 - [ ] Fixed-size arrays (#6437)
 - [x] Address #4044
 - [x] More diverse views permitting an `AbstractVector` index? (These would not be "strided".)
 - [x] Move `Colon` translation out of the parser (#10331)

##### Opportunities
 - [ ] negated indexing, #1032
 - [x] easier indexing for `AbstractArray`s, #10525

[ArrayViewsAPL](https://github.com/timholy/ArrayViewsAPL.jl) is something I've not yet broadly announced. While the APL in the package's title is in reference to #5949 (for which it can be a test bed to see how we'd like it and how much would break), its real purpose is to exploit stagedfunctions for creating efficient and general view operations. Please see the README for explanations.

**Comment by ViralBShah** [comment]
I have been following from a distance, but I am wondering if we are any closer now than 3 months ago. Quite a bit has happened with staged functions, sub arrays and cartesian iterators since then, which makes me hopeful that we are closer to replacing array indexing with views. Is it likely we can achieve this in 0.4?

**Comment by andreasnoack** [comment]
Some and hopefully most of the work should be done in #9150. The main issue is to handle `Colon` within Julia instead of in the parser. I've talk with @jakebolewski about fixing that.

**Comment by timholy** [comment]
In a sense this is already done, other than syntax (meaning `A[:,j]` gets replaced by `slice(A, :, j)`).

But it's still a little scary given "deep" bugs in stagedfunctions, #8504 and #8553. If those had been fixed, we surely would have had this functionality months ago.

**Comment by timholy** [comment]
Oh, and I forgot perhaps even the most important one: it would be insane to turn `A[:,j]` into `slice(A, :, j)` until #8227 (or alternate implementation) gets merged.

**Comment by jiahao** [comment]
@timholy I think you meant some other issue besides #8553

**Comment by timholy** [comment]
Indeed I did, thanks for catching. (Corrected above.)

**Comment by ViralBShah** [comment]
It looks like much of this will make its way into 0.4. Should we refactor this issue into the bits that we want in 0.4, and a separate issue for what will be in 0.5?

**Comment by timholy** [comment]
Indeed, the large majority has been in 0.4 for some time---that's what all the checkmarks at the top are for :smile:.

If you want to split out separate issues for the remaining items, I'm fine with that, but I don't really see the point.

**Comment by mschauer** [comment]
@lindahua Regarding your remark in the beginning, the issue on ``...`` was https://github.com/JuliaLang/julia/issues/5405

**Comment by timholy** [comment]
#10525 was long overdue for a spot on that list, so I added it.

**Comment by ViralBShah** [comment]
I was just initially puzzled at seeing the 0.5 milestone. We can leave it as it is.

**Comment by ViralBShah** [comment]
The question I really had was - from a 0.4 perspective, which of the unchecked ones we want to get done, or are we already there?

**Comment by blakejohnson** [comment]
I think we should still aim for extensible bounds checking removal, #7799, in 0.4.

**Comment by timholy** [comment]
I was puzzled about the 0.5 milestone too. I wondered if you had changed it (I didn't). That said, I think we won't get most of the remaining items by 0.4, so bumping the milestone seems reasonable.

Realistically, I expect us to check only one more box: I think we **will** get "sweet custom array types" (aka #10525, hopefully supported by #10911 if I can get my act together in time). This is a really big step---one that I did not anticipate at the time I opened this issue---and it will be amazing to have. That would also open the way for fixing `reshape` (#10507), but I'd be a little reluctant to add that kind of functionality at a late date. I just tagged that PR as 0.5 to clarify my current thoughts about it.

Re "return views from indexing": I think the big show-stopper is #7799, since our views don't check bounds (in my opinion, we'd have a catastrophic loss of safety if we switched to returning views before addressing that issue). It's also worth reminding folks that @carlobaldassi has raised a number of concerns specifically about `BitArrays` that, to my knowledge, we haven't really addressed (see posts higher up in this issue). However, if we _can_ satisfy ourselves about these two issues, then there's a lot that can happen relatively quickly (#10331, and returning views from indexing).

**Comment by pao** [comment]
> I wondered if you had changed it

In case you hadn't seen it, this is in the issue's log, squeezed between comments--it was changed on March 7 by @vtjnash.

**Comment by StefanKarpinski** [comment]
@vtjnash went around and randomized all the milestones :-|

**Comment by mbauman** [comment]
> I think the big show-stopper is #7799, since our views don't check bounds (in my opinion, we'd have a catastrophic loss of safety if we switched to returning views before addressing that issue).

I'm looking at this right now in the context of #10525.  I think I may be able to rectify this since it puts `unsafe_getindex` on firmer ground.  It sure would be a lot nicer with #7799, though.

(`SubArray` *almost* checks bounds right now, though.  It does so upon construction, and then it indexes into the parent array with bounds checks on.  The trouble is that in a multidimensional indexing expression, one of the indices may be out of bounds and it may return spurious data.)

**Comment by carlobaldassi** [comment]
> a number of concerns specifically about `BitArrays` that, to my knowledge, we haven't really addressed (see posts higher up in this issue).

To get back on that, my current thinking is that a lot of methods should be specialized to work on BitArray Views efficiently. It's going to take time -- and to increase `test/bitarray.jl` execution time considerably -- but in the end I think it's also going to improve performance in most common cases by allowing to avoid temporaries (e.g. `sum(B[a:b])` and similar).

BTW I'm assuming that in most relevant cases views of views can be flattened, otherwise this is probably not going to work.

The only issue which I don't think we can really solve is treating efficiently views with generic, non contiguous indexing. However, this is only going to make a real difference when indexing repeatedly into the view, and maybe for nested views.

**Comment by prcastro** [comment]
I believe the last two items could be closed

**Comment by mbauman** [comment]
Superseded by #13157.  If I missed from this issue, please add it there.
