### ISSUE TITLE
Missing emacs-like key-bindings (available in readline)

### ISSUE THREAD

**Issue by rfourquet** [JuliaLang/julia#8447]
- [x] kill ring: M-y (after a C-y) to yank previous killed entries (#23377)
- [x] all deleted things (but characters) pushed onto the kill-ring (M-d, C-u, etc.) (#23593)
- [x] first/last history entries via M-< and M-> (#22829 and #23213)
- [x]  undo (C-/ or C-_) (#9596, see #23590 for "redo")
- [x] insert last word from previous command (M-.) (#33749)
- [x] word transposition (M-t) (#23378)
- [x] change case (M-c, M-u, M-l) (#23379)

**Comment by rfourquet** [comment]
Can finally be closed after 5 years :)
Of course, this doesn't mean that no more improvements are planned ;-)
